Repository telstra/open-kilda, pull requests merged in 2018-02, with the labels that each got.

#321 Add flow DELETE sequence diagramm
  docs/design/usecase/flow-crud-create-full.png
  docs/design/usecase/flow-crud-create-full.txt
  docs/design/usecase/flow-crud-delete-full.png
  docs/design/usecase/flow-crud-delete-full.txt
  docs/design/usecase/flow-crud.md
Labels: area/docs

#319 Make TopologyEngine properly handle links with no latency set.
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowPathTest.java
  services/topology-engine/queue-engine/topologylistener/flow_utils.py
Labels: bug

#322 Add the correlationId to the logger context (MDC) for Northbound.
  services/src/northbound/src/main/java/org/openkilda/northbound/config/WebConfig.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
  services/src/northbound/src/main/resources/log4j2.xml
Labels: techdebt
