Repository telstra/open-kilda, pull requests merged in 2018-08, with the labels that each got.

#1101 Handle IOException in stats CacheBolt method initFlowCache.
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/bolts/CacheBolt.java
Labels: Ready to Merge

#1098 Reformat docker files #1087
  base/base-builder/Dockerfile
  base/base-java/Dockerfile
  base/base-maven/Dockerfile
  base/kilda-base-ubuntu/Dockerfile
  services/mininet/Dockerfile
  services/src/atdd-staging/Dockerfile
  services/src/openkilda-gui/Dockerfile
  services/topology-engine-rest/Dockerfile
  services/topology-engine/Dockerfile
  services/wfm/Dockerfile
Labels: Next Release, area/cicd

#1097 Flow path UI changes
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowdetails.js
Labels: C/GUI, Next Release

#1096 API call to get flow path data from NB (North Bound)
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/FlowController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowPathConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPathInfoData.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPathNode.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPayload.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/FlowsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/utility/ApplicationProperties.java
  services/src/openkilda-gui/src/main/resources/application.properties
  templates/templates/openkilda-gui/application.properties.j2
Labels: C/GUI, Next Release, area/gui

#1066 Change bandwidth type from int to long.
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowCrudBasicRunTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowIgnoreBandwidthTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowPathTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/Flow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/FlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallIngressFlowTest.java
  services/src/northbound/src/test/java/org/openkilda/northbound/controller/TestMessageMock.java
  services/src/pce/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/pce/src/main/java/org/openkilda/pce/api/FlowAdapter.java
  services/src/pce/src/main/java/org/openkilda/pce/cache/FlowCache.java
  services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/PathComputer.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/ResourceCacheTest.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerMock.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/PathComputerMock.java
Labels: Next Release

#1071 Prevent usage incomplete flow object in reroute
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRerouteRequest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/SplitterBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/cache/CacheTopologyTest.java
Labels: C/CACHE, C/FLOW, C/NB, Next Release

#1082 Move tag extension from 'extensTion.tags' package to 'extension.tags'
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/tags/Tag.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/tags/Tags.groovy
  services/src/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: Next Release, area/testing

#1089 Avoid resource leaks in FlowCache
  services/src/pce/src/main/java/org/openkilda/pce/cache/FlowCache.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/FlowCacheTest.java
Labels: Next Release, Ready to Merge

#1091 Fix/bandwidth update
  services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java
  services/src/pce/src/test/java/org/openkilda/pce/algo/SimpleGetShortestPathTest.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/PathComputerMock.java
Labels: C/FLOW, Next Release

#1093 Add basic flow C(R)UD operations test into TE
  services/topology-engine/queue-engine/topologylistener/flow_utils.py
  services/topology-engine/queue-engine/topologylistener/model.py
  services/topology-engine/queue-engine/topologylistener/tests/data/flow-create-request.json
  services/topology-engine/queue-engine/topologylistener/tests/share.py
  services/topology-engine/queue-engine/topologylistener/tests/test_config.py
  services/topology-engine/queue-engine/topologylistener/tests/test_flow.py
  services/topology-engine/queue-engine/topologylistener/tests/test_isl.py
Labels: Next Release

#1058 #1050: Fixed exception in OFELinkBolt +refactoring
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/OFELinkBoltTest.java
Labels: C/EVENT, Next Release

#1106 TPE dependent property removed
  services/src/openkilda-gui/src/main/java/org/openkilda/utility/ApplicationProperties.java
Labels: C/GUI, Next Release, area/gui, assigned

#1084 Remove upper py2neo version limit
  services/topology-engine-rest/Dockerfile
  services/topology-engine-rest/app/app/neo4j_tools.py
  services/topology-engine-rest/app/app/topology.py
  services/topology-engine/Dockerfile
  services/topology-engine/queue-engine/topologylistener/db.py
  services/topology-engine/queue-engine/topologylistener/isl_utils.py
Labels: C/TE, Next Release

#1109 Add a correlation id header to a response.
  services/src/northbound/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationFilter.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationId.java
Labels: C/NB, Ready to Merge, area/northbound

#1105 Fix FL config parsing
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/config/provider/ConfigurationProvider.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaConsumerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaProducerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchEventCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/main/resources/floodlightkilda.properties
  services/src/floodlight-modules/src/main/resources/logback.xml
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/config/provider/ConfigurationProviderTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  templates/templates/floodlight/floodlightkilda.properties.j2
Labels: C/FL, Next Release, area/floodlight

#1077 Build process changes to include Openkilda-gui
  docker-compose.yml
  services/src/openkilda-gui/README.md
  services/src/openkilda-gui/docker-compose.yml
  services/src/openkilda-gui/src/main/resources/application.properties
Labels: Ready to Merge

#1114 #1107 Remove duplicated DTO, add api serialization tests
  services/src/api/pom.xml
  services/src/api/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/api/src/main/java/org/openkilda/northbound/dto/BatchResults.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/flows/FlowValidationDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/flows/PathDiscrepancyDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/flows/UniFlowVerificationOutput.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/flows/VerificationOutput.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/links/LinkDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/links/LinkPropsDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/links/PathDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/switches/RulesSyncResult.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/switches/RulesValidationResult.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/switches/SwitchDto.java
  services/src/api/src/test/java/org/openkilda/northbound/dto/JsonSerializationTest.java
  services/src/northbound/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/LinkController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/SwitchController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/LinkMapper.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/LinkPropsMapper.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/src/northbound/src/main/java/org/openkilda/northbound/dto/LinkPropsDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/dto/LinksDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/dto/PathDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/dto/SwitchDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/LinkPropsResult.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/LinkService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/northbound/src/test/java/org/openkilda/northbound/controller/SwitchControllerTest.java
  services/src/northbound/src/test/java/org/openkilda/northbound/dto/LinkPropsDtoTest.java
  services/src/northbound/src/test/java/org/openkilda/northbound/dto/LinksDtoTest.java
  services/src/northbound/src/test/java/org/openkilda/northbound/service/LinkServiceTest.java
Labels: C/NB, Ready to Merge, area/api

#1120 Resolve a flow controller issue with truncating @PathVariable if it contains dot.
  services/src/atdd/pom.xml
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/FlowController.java
Labels: Ready to Merge

#1124 Fixing query for the possibility of injections.
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
Labels: Ready to Merge

#1112 Fix path was not found issue
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
Labels: Ready to Merge

#1126 Docker raise warning for empty line joined via '\'
  base/kilda-base-ubuntu/Dockerfile
Labels: Ready to Merge

#1136 Change HTTP 404 Error code for "Path not found" on update flow.
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
Labels: C/FLOW, Ready to Merge

#1145 Fix bw type from int to long in cucumber step
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
Labels: Ready to Merge, area/testing

#1147 409 error code, if port/vlan occupied by another flow (update case)
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
Labels: Ready to Merge

#1139 409 error on Port/Vlan occupied by another flow
  services/src/northbound/src/main/java/org/openkilda/northbound/service/BasicService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
Labels: Ready to Merge

#1142 #1069 remove VariableDeclarationUsageDistance suppress lines for tests.
  services/src/atdd/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/messaging/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/pce/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
Labels: Ready to Merge

#1140 #590 remove unit tests for non-existent methods in FL.
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationFlowTest.java
Labels: Ready to Merge

#1048 Add per flow periodic ping activation switch
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/helpers/FlowSet.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowCrudBasicRunTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowFfrTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowIgnoreBandwidthTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowPingTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/StormTopologyLcm.java
  services/src/atdd/src/test/java/org/openkilda/flow/FlowUtils.java
  services/src/messaging/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/Flow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayloadToFlowConverter.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/FlowInfoDataTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/FlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/info/flow/FlowInfoDataTest.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound/src/test/java/org/openkilda/northbound/controller/TestMessageMock.java
  services/src/pce/src/main/java/org/openkilda/pce/api/FlowAdapter.java
  services/src/pce/src/main/java/org/openkilda/pce/cache/FlowCache.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/ResourceCacheTest.java
  services/topology-engine-rest/app/app/topology.py
  services/topology-engine/queue-engine/topologylistener/flow_utils.py
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
  services/topology-engine/queue-engine/topologylistener/model.py
  services/wfm/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java
Labels: Ready to Merge

#1143 Enabled mandatory run update-props as part of make targets
  .gitignore
  .travis.yml
  Makefile
  base/hacks/load_kilda_dev_ubuntu.sh
  services/logstash/Dockerfile.example
  services/logstash/etc/logstash/conf.d/logstash.conf.example
  services/mininet/app/log.json.example
  services/src/atdd-staging/kilda.properties.example
  services/src/atdd-staging/log4j2.xml.example
  services/src/floodlight-modules/src/main/resources/floodlightkilda.properties.example
  services/src/floodlight-modules/src/main/resources/logback.xml.example
  services/src/northbound/src/main/resources/log4j2.xml.example
  services/src/northbound/src/main/resources/northbound.properties.example
  services/src/openkilda-gui/src/main/resources/application.properties.example
  services/storm/log4j2/cluster.xml.example
  services/storm/log4j2/worker.xml.example
  services/topology-engine-rest/app/log.json.example
  services/topology-engine-rest/app/topology_engine_rest.ini.example
  services/topology-engine/queue-engine/log.json.example
  services/topology-engine/queue-engine/topology_engine.ini.example
  services/wfm/src/main/resources/topology.properties.example
  templates/defaults/main.yaml
  templates/templates/floodlight/floodlightkilda.properties.j2
Labels: Ready to Merge

#1141 Added auto upload of kibana dashboards to ELK
  Makefile
  tools/elk-dashboards/Makefile
  tools/elk-dashboards/dashboard/db_31fb0820-93e1-11e8-b468-9bf0373c963a.json
  tools/elk-dashboards/dashboard/db_9b4baf30-7606-11e8-b23f-538771841d2c.json
  tools/elk-dashboards/dashboard/db_b6a75a70-42cd-11e8-8a3b-03954453f1cc.json
  tools/elk-dashboards/dashboard/db_d8c91f30-4fe3-11e8-a981-f39b47bf4e67.json
  tools/elk-dashboards/index_pattern.json
  tools/elk-dashboards/load.sh
  tools/elk-dashboards/search/search_1fb3d0f0-425d-11e8-86e2-f5620c719589.json
  tools/elk-dashboards/search/search_4c213750-42b1-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/search/search_5cb3ee60-f16b-11e7-a202-e79f0134df49.json
  tools/elk-dashboards/search/search_88dffe30-42cd-11e8-8a3b-03954453f1cc.json
  tools/elk-dashboards/search/search_8dd0d860-3bd4-11e8-ae99-81188e3024ba.json
  tools/elk-dashboards/search/search_fa81a1f0-f229-11e7-9f55-7bb8fa2a1bf7.json
  tools/elk-dashboards/visualization/vis_03da69c0-42cb-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/visualization/vis_0dbf2e70-f209-11e7-9052-7bb5aee88040.json
  tools/elk-dashboards/visualization/vis_1527faf0-3bf8-11e8-a58d-b1da056b2e80.json
  tools/elk-dashboards/visualization/vis_2489ab10-f210-11e7-9052-7bb5aee88040.json
  tools/elk-dashboards/visualization/vis_378dcee0-42be-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/visualization/vis_4759bf90-396e-11e8-9bae-5f7b4e60550b.json
  tools/elk-dashboards/visualization/vis_8e63d120-3bf6-11e8-916f-3fb185ebad8c.json
  tools/elk-dashboards/visualization/vis_b9dbc3c0-42c8-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/visualization/vis_bd994530-f16c-11e7-a202-e79f0134df49.json
  tools/elk-dashboards/visualization/vis_bdff5b80-3bd2-11e8-ac01-c9e1811c182f.json
  tools/elk-dashboards/visualization/vis_d0175150-3c41-11e8-9edc-9b7acf4657b4.json
  tools/elk-dashboards/visualization/vis_d2499a10-3bd2-11e8-ac01-c9e1811c182f.json
Labels: Ready to Merge

#1148 Rework docker files using best practices
  Makefile
  base/hacks/kilda-bins.download.sh
  base/hacks/kilda-bins.requirements.txt
  base/kilda-base-ubuntu/Dockerfile
  services/hbase/Dockerfile
  services/hbase/ansible/deploy.yml
  services/kafka/Dockerfile
  services/kafka/ansible/deploy.yml
  services/neo4j/Dockerfile
  services/neo4j/ansible/deploy.yml
  services/opentsdb/Dockerfile
  services/opentsdb/ansible/deploy.yml
  services/storm/Dockerfile
  services/storm/ansible/deploy.yml
  services/topology-engine-rest/Dockerfile
  services/zookeeper/Dockerfile
  services/zookeeper/ansible/deploy.yml
Labels: Ready to Merge

#1092 Added test for isl oversubscribing via reroute. Added utility classes
  services/src/atdd-staging/src/main/resources/cucumber.properties
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/config/HelpersConfig.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/BandwidthSpec.groovy
  services/src/functional-tests/src/test/resources/spring-context.xml
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowReroutePayload.java
  services/src/test-library/pom.xml
  services/src/test-library/src/main/java/org/openkilda/testing/config/DefaultServiceConfig.java
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseNeoImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Ready to Merge, area/testing

#1155 Feature/change port status fix
  docs/design/usecase/change-port-status.md
  docs/design/usecase/change-port-status.png
  docs/design/usecase/change-port-status.txt
  services/src/api/src/main/java/org/openkilda/northbound/dto/switches/PortDto.java
  services/src/atdd/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/atdd/src/main/java/org/openkilda/atdd/utils/controller/PortEntry.java
  services/src/atdd/src/main/java/org/openkilda/atdd/utils/controller/SwitchEntry.java
  services/src/atdd/src/test/java/org/openkilda/SwitchesUtils.java
  services/src/atdd/src/test/java/org/openkilda/atdd/SwitchConfigurationTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/utils/controller/ControllerUtils.java
  services/src/atdd/src/test/resources/features/mvp.1/SwitchPortConfiguration.feature
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/PortConfigurationRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/PortStatus.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/switches/PortConfigurationResponse.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/switches/PortConfigurationPayload.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/SwitchController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: C/FL, C/NB, Ready to Merge

#1154 Test for successful reroute case
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/BandwidthSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseNeoImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Ready to Merge, area/testing

#1158 Added sonarcloud test in CICD pipeline
  .travis.yml
  README.md
Labels: Next Release, Ready to Merge, area/cicd

#1166 Changed .travis.yaml for parallel running
  .travis.yml
Labels: Ready to Merge

#1173 Adding feature to change port status from Kilda GUI
  services/src/openkilda-gui/pom.xml
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/SwitchController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/PortConfiguration.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/ConfiguredPort.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/SwitchIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/log/constants/ActivityType.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/utility/ApplicationProperties.java
  services/src/openkilda-gui/src/main/resources/application.properties.example
  services/src/openkilda-gui/src/main/resources/db/import-script_4.sql
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowobject.js
  services/src/openkilda-gui/src/main/resources/ui/js/ports/portdetails.js
  services/src/openkilda-gui/src/main/resources/ui/js/ports/portobject.js
  services/src/openkilda-gui/src/main/resources/ui/templates/port/portdetails.html
  templates/templates/openkilda-gui/application.properties.j2
Labels: C/GUI, Ready to Merge

#1181 Fix duplication of ISL records in DiscoveryManager.
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/OFELinkBoltState.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OfeLinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
Labels: C/EVENT, Ready to Merge

#1185 Proper passing of SwitchId values to cypher query.
  services/src/messaging/src/main/java/org/openkilda/messaging/model/NetworkEndpointMask.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java
Labels: C/NBWORKER, Ready to Merge

#1201 [WFM/Cache topology] Add Reroute throttling bolt.
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/FlowThrottlingBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/StreamType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/service/ExtendableTimeWindow.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/service/ReroutesThrottling.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/topology/cache/service/ExtendableTimeWindowTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/cache/service/ReroutesThrottlingTest.java
  services/wfm/src/test/resources/topology.properties
  templates/defaults/main.yaml
  templates/templates/wfm/topology.properties.j2
Labels: C/CACHE, Ready to Merge

#1207 adding feature to display RX/TX flow path graph
  services/src/openkilda-gui/src/main/resources/ui/css/custom.css
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flow-graph-stats.js
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowdetails.js
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowobject.js
  services/src/openkilda-gui/src/main/resources/ui/templates/flows/flowdetails.html
Labels: Ready to Merge

#1175 Added proper neo.uri to templates
  templates/defaults/main.yaml
  templates/templates/atdd-staging/kilda.properties.j2
Labels: Ready to Merge, area/testing

#1184 Add test to verify available bandwidth on ISLs
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/Wrappers.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/links/LinkPropertiesSpec.groovy
Labels: Ready to Merge, area/testing

#1203 Update test framework to support partially-defined links.
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManagerImpl.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/LinkPropertiesSteps.java
  services/src/atdd-staging/src/main/resources/features/northbound.feature
Labels: Next Release, area/testing

#1189 Added test for reroute behavior when link fails and no alt paths available
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/AutoReroutesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/flows/IntentionalRerouteSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Next Release, area/testing

#1138 #950 delete rules for invalid switch.
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchNotFoundException.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/web/FlowsResource.java
Labels: C/FL, Next Release

#1156 #1051 Fix db queries in TE.
  services/topology-engine/queue-engine/topologylistener/flow_utils.py
Labels: Next Release

#1167 #1165 Fix the response for the invalid port number.
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
Labels: Next Release

#1169 Add make clean phase.
  .gitignore
  Makefile
  README.md
  base/hacks/storm.requirements.download.sh
Labels: Ready to Merge

#1179 Changed external NB port for all-in-one env from 8088 to 8080
  .travis.yml
  docker-compose.yml
  services/src/atdd/src/test/java/org/openkilda/DefaultParameters.java
  templates/defaults/main.yaml
Labels: Ready to Merge

#1182 Fix the type of max bandwidth in neo4j.
  services/topology-engine/queue-engine/topologylistener/model.py
Labels: C/TE, Next Release

#1197 #1153 Fix the computing of the path if ISL cost is equal to MAX_INT.
  services/src/pce/src/main/java/org/openkilda/pce/algo/SimpleGetShortestPath.java
Labels: Next Release

#1222 Enhancement in stats graphs to zoom vertically and remove draw points
  services/src/openkilda-gui/src/main/resources/ui/js/common.js
Labels: Next Release

#1152 Deny creation of self-looped ISL
  services/mininet/kilda/mininet/rest.py
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/IslSteps.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/IslMovingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/flows/IntentionalRerouteSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OfeLinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/OfeLinkBoltTest.java
Labels: C/EVENT, Ready to Merge

#1206 #308 Rename ImmutablePair to FlowPair.
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd-staging/src/test/java/org/openkilda/atdd/staging/service/StubServiceFactory.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowIgnoreBandwidthTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowPathTest.java
  services/src/atdd/src/test/java/org/openkilda/atdd/StormTopologyLcm.java
  services/src/atdd/src/test/java/org/openkilda/flow/FlowUtils.java
  services/src/atdd/src/test/java/org/openkilda/topo/TopologyHelp.java
  services/src/messaging/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/FlowDump.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/NetworkInfoData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/flow/FlowInfoData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowPair.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/info/flow/FlowInfoDataTest.java
  services/src/pce/src/main/java/org/openkilda/pce/cache/FlowCache.java
  services/src/pce/src/main/java/org/openkilda/pce/cache/ResourceCache.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/PathComputer.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/FlowCacheTest.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/ResourceCacheTest.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerMock.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerTest.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/topology/TopologyEngineService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/topology/TopologyEngineServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/service/CacheWarmingService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/cache/CacheTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/PathComputerMock.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: Ready to Merge

#1223 Fixing multiple tab issue in port status update from gui
  services/src/openkilda-gui/src/main/resources/ui/js/isl/isl-graph-stats.js
  services/src/openkilda-gui/src/main/resources/ui/js/ports/port-graph.js
  services/src/openkilda-gui/src/main/resources/ui/js/ports/portdetails.js
  services/src/openkilda-gui/src/main/resources/ui/js/ports/portobject.js
  services/src/openkilda-gui/src/main/resources/ui/js/useractivity/useractivity.js
Labels: Next Release

#1190 #907 Fix the error display when using incorrect character in TE.
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
Labels: Next Release

#1211 #902 Fix 500 error when creating link props.
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SwitchId.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
Labels: Ready to Merge

#1200 Fix typos in readme files.
  docs/README
  docs/README.md
  docs/design/README.MD
  docs/design/usecase/flow-crud.md
Labels: Ready to Merge
