Repository telstra/open-kilda, pull requests merged in 2018-07, with the labels that each got.

#956 Create flow functionality and bug fixes
  services/src/openkilda-gui/src/main/java/org/openkilda/OpenKildaApplication.java
  services/src/openkilda-gui/src/main/java/org/openkilda/auth/interceptor/RequestInterceptor.java
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/BaseController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/FlowController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/HomeController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/LoginController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/handler/error/MyAccessDeniedHandler.java
  services/src/openkilda-gui/src/main/java/org/openkilda/helper/RestClientManager.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/FlowEndpoint.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/FlowsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/security/TwoFactorUtility.java
  services/src/openkilda-gui/src/main/java/org/openkilda/security/filter/LoggingFilter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/security/mapper/CustomExceptionMapper.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/AuthPropertyService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/utility/ApplicationProperties.java
  services/src/openkilda-gui/src/main/resources/application.properties.example
  services/src/openkilda-gui/src/main/resources/db/import-script_3.sql
  services/src/openkilda-gui/src/main/resources/ui/css/custom.css
  services/src/openkilda-gui/src/main/resources/ui/js/common.js
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowObject.js
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowdetails.js
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flows.js
  services/src/openkilda-gui/src/main/resources/ui/js/useractivity/useractivity.js
  services/src/openkilda-gui/src/main/resources/ui/templates/flows/addflow.html
  services/src/openkilda-gui/src/main/resources/ui/templates/flows/flowdetails.html
  services/src/openkilda-gui/src/main/resources/ui/templates/flows/flows.html
  templates/templates/openkilda-gui/application.properties.j2
  templates/templates/openkilda-gui/logback.xml.j2
Labels: C/GUI, Next Release

#949 Remove ancient WFM POC
  services/wfm/app/wfm-poc.py
  services/wfm/app/wfm.py
Labels: Next Release, Ready to Release

#975 Disable flow verification feature
  services/src/atdd/src/test/resources/features/mvp.1/FlowVerification.feature
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/FlowController.java
Labels: C/NB, Next Release, Ready to Release

#957 Removed redundant 'rollback of flow path' mechanism from Cache Topology
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
Labels: C/CACHE, Next Release, Ready to Merge, refactor

#920 ISL status is set to Moved on physically re-plugging of ISL
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/IslSteps.java
  services/src/atdd-staging/src/main/resources/features/failsafe_behaviour.feature
  services/src/atdd/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/atdd/src/test/java/org/openkilda/KafkaParameters.java
  services/src/atdd/src/test/java/org/openkilda/KafkaUtils.java
  services/src/atdd/src/test/java/org/openkilda/TopologyCtrlProcessingException.java
  services/src/atdd/src/test/java/org/openkilda/topo/TestUtils.java
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/AbstractBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
Labels: C/EVENT, Next Release, area/testing

#979 Remove noisy ISL discovery logging
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
Labels: C/FL, Next Release, Ready to Merge

#980 Remove unused tests code
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/FloodlightTestCase.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/MockFloodlightProvider.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/MockSwitchManager.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationFlowTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketOutTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/PushSchemeOutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/ReplaceSchemeOutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlightcontroller/core/test/MockScheduledExecutor.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlightcontroller/core/test/MockThreadPoolService.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlightcontroller/core/test/PacketFactory.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlightcontroller/core/test/TestEventLoop.java
Labels: Ready to Merge

#982 Ansible neo4j tempfix
  services/neo4j/ansible/deploy.yml
Labels: Next Release

#946 Added possibility to remove meter from the switch
  docs/design/usecase/meter-delete.md
  docs/design/usecase/meter-delete.png
  docs/design/usecase/meter-delete.txt
  services/src/api/src/main/java/org/openkilda/northbound/dto/switches/DeleteMeterResult.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/DeleteMeterRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/switches/DeleteMeterResponse.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/SwitchController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: C/FL, C/NB, Next Release, Ready to Merge

#992 Cleanup POMs
  services/src/api/pom.xml
  services/src/atdd-staging/pom.xml
  services/src/atdd/pom.xml
  services/src/atdd/src/test/java/org/openkilda/atdd/StormTopologyLCM.java
  services/src/configuration/pom.xml
  services/src/floodlight-modules/pom.xml
  services/src/messaging/pom.xml
  services/src/northbound/pom.xml
  services/src/pce/pom.xml
  services/src/pce/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/pce/src/test/java/org/openkilda/pce/cache/FlowCacheTest.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/NetworkCacheTest.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/ResourceCacheTest.java
  services/src/pom.xml
  services/wfm/pom.xml
Labels: Ready to Merge, refactor

#999 Disable URL templating in swagger Docket bean
  services/src/northbound/src/main/java/org/openkilda/northbound/config/SwaggerConfig.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/FlowController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/SwitchController.java
Labels: Ready to Merge

#1004 #990: Add test to verify a case when link props have non-numeric values
  services/src/atdd-staging/src/main/resources/features/northbound.feature
Labels: Next Release, Ready to Merge, area/testing

#985 Avoid force rediscovery during FL - Event/WFM synchronization process.
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerMock.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/NetworkDumpBeginMarker.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/NetworkDumpEndMarker.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/NetworkDumpPortData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/NetworkDumpSwitchData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/SwitchInfoData.java
  services/wfm/pom.xml
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/OFELinkBoltTest.java
Labels: C/EVENT, C/FL, C/FLOW, C/STATS, Next Release

#995 Guaranteed delivery of ISL disco packets
  docs/design/usecase/discovery/isl-disco-guaranteed-delivery.md
  docs/design/usecase/discovery/isl-disco-guaranteed-delivery.png
  docs/design/usecase/discovery/isl-disco-guaranteed-delivery.txt
  docs/design/usecase/discovery/network-discovery.md
  docs/design/usecase/discovery/network-discovery.png
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/discovery/DiscoverIslCommandData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/discovery/DiscoPacketSendingConfirmation.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/discovery/DiscoverISLCommandDataTest.java
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/simulator/bolts/SpeakerBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryLinkTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
Labels: C/EVENT, C/FL, C/STATS, Next Release, Ready to Merge

#1018 Upgrade springfox library to 2.9.2 version
  services/src/northbound/pom.xml
Labels: Ready to Merge

#954 Issue/downgrade bandwidth
  services/src/atdd/src/test/resources/features/mvp.1/FlowCrudBasicRun.feature
  services/src/pce/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/pce/src/main/java/org/openkilda/pce/Utils.java
  services/src/pce/src/main/java/org/openkilda/pce/algo/SimpleGetShortestPath.java
  services/src/pce/src/main/java/org/openkilda/pce/model/AvailableNetwork.java
  services/src/pce/src/main/java/org/openkilda/pce/model/SimpleIsl.java
  services/src/pce/src/main/java/org/openkilda/pce/model/SimpleSwitch.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/PathComputer.java
  services/src/pce/src/test/java/org/openkilda/pce/algo/SimpleGetShortestPathTest.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerMock.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/PathComputerMock.java
Labels: C/CACHE, C/FLOW, Next Release

#927 #919: Added test for updating bandwidth
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManager.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManagerImpl.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/traffexam/model/Bandwidth.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd-staging/src/main/resources/features/flow_crud.feature
  services/src/atdd-staging/src/test/java/org/openkilda/atdd/staging/tests/flow_crud/FlowCrudOverActiveSwitchesTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
Labels: Next Release, area/testing

#1002 Floodlight : monitorable and guaranteed processing of incoming messages.
  docs/design/solutions/floodlight/floodlight-collaboration-new.png
  docs/design/solutions/floodlight/floodlight-collaboration-new.txt
  docs/design/solutions/floodlight/floodlight-collaboration-old.png
  docs/design/solutions/floodlight/floodlight-collaboration-old.txt
  docs/design/solutions/floodlight/floodlight-guaranteed-processing.md
  floodlight-collaboration-old.png
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/config/KafkaFloodlightConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/Consumer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/ConsumerContext.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/Context.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaConsumerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaProducerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/TestAwareConsumer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/TestAwareProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/producer/Producer.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/config/provider/ConfigurationProviderTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/KafkaOffsetRegistryTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
Labels: C/FL, Ready to Merge

#1015 Revert "As NEO4J maintainers forgot to renew they SSL cert, we have t…
  services/neo4j/ansible/deploy.yml
Labels: Ready to Merge

#1028 Fixed ambiguous step name. Fixed method for searching a-switch isls
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManagerImpl.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd-staging/src/main/resources/features/flow_crud.feature
Labels: Ready to Merge, area/testing

#1021 Atdd staging/bugfix 1019
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/SwitchSteps.java
  services/src/atdd-staging/src/main/resources/features/northbound.feature
Labels: area/testing

#1024 Add validation of flow ports against conflicts with ISL ports.
  services/src/atdd/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/atdd/src/test/java/org/openkilda/atdd/FlowCrudBasicRunTest.java
  services/src/atdd/src/test/resources/features/mvp.1/FlowCrudBasicRun.feature
  services/src/atdd/src/test/resources/features/mvp.1/FlowFFR.feature
  services/src/atdd/src/test/resources/features/mvp.1/FlowPath.feature
  services/src/atdd/src/test/resources/features/mvp.1/FlowReinstall.feature
  services/src/atdd/src/test/resources/features/mvp.1/FlowVerification.feature
  services/src/atdd/src/test/resources/features/mvp.1/NorthboundRun.feature
  services/src/atdd/src/test/resources/flows/non-standard-cookies-flow.json
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/NeoDriver.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/PathComputer.java
  services/src/pce/src/main/java/org/openkilda/pce/provider/TopologyRepository.java
  services/src/pce/src/test/java/org/openkilda/pce/provider/PathComputerMock.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/PathComputerMock.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/FLOW, Ready to Merge

#1025 Add "How to run ATDD" section to readme file
  README.md
Labels: Next Release, Ready to Merge

#1047 Fixed failsafe test to only pick switches with traffgens
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/helpers/FlowSet.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManagerImpl.java
Labels: Ready to Merge, area/testing

#1046 Added fixture extensions. Added test for link props search to showcase
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/fixture/SetupOnce.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/fixture/SetupOnceExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/fixture/TestFixture.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/fixture/TestFixtureExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/spring/SpringContextExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/northbound/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
  services/src/functional-tests/src/test/resources/spring-context.xml
Labels: area/testing

#1044 Fixed the issue when floodlight kafka consumer rejects some messages from kafka because no executor available
  docs/design/solutions/floodlight/floodlight-collaboration-new.png
  docs/design/solutions/floodlight/floodlight-collaboration-new.txt
  docs/design/solutions/floodlight/floodlight-collaboration-old.png
  docs/design/solutions/floodlight/floodlight-collaboration-old.txt
  docs/design/solutions/floodlight/floodlight-guaranteed-processing.md
  floodlight-collaboration-old.png
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/config/KafkaFloodlightConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/Consumer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/ConsumerContext.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/Context.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaConsumerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaProducerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/TestAwareConsumer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/TestAwareProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/producer/Producer.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/config/provider/ConfigurationProviderTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/KafkaOffsetRegistryTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
Labels: C/FL, LGTM

#1043 Increase switch validation verbosity
  services/topology-engine/queue-engine/topologylistener/flow_utils.py
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
Labels: C/TE, Ready to Merge

#1013 Add support of value validation for configuration beans.
  services/src/atdd/src/main/java/org/openkilda/topo/builders/TeTopologyParser.java
  services/src/configuration/pom.xml
  services/src/configuration/src/main/java/org/openkilda/config/KafkaConfig.java
  services/src/configuration/src/main/java/org/openkilda/config/provider/ConfigurationException.java
  services/src/configuration/src/main/java/org/openkilda/config/provider/ValidatingConfigurationProvider.java
  services/src/configuration/src/test/java/org/openkilda/config/provider/ValidatingConfigurationProviderTest.java
  services/src/floodlight-modules/pom.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/config/provider/ConfigurationProvider.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/HeartBeat.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaConsumerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaProducerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationServiceConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsServiceConfig.java
  services/src/pom.xml
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/config/provider/ConfigurationProvider.java
Labels: C/CACHE, C/EVENT, C/FL, C/FLOW, Ready to Merge, feature

#1052 Decrease parallelism of opentsdb topology on dev env
  services/wfm/src/main/resources/topology.properties
  templates/defaults/main.yaml
  templates/templates/wfm/topology.properties.j2
Labels: Ready to Merge

#1033 #1038: Add cleanup step to 'Remove meter on switch' scenario
  services/src/atdd-staging/src/main/resources/features/northbound.feature
Labels: Ready to Merge, area/testing

#1056 Added IslUtils to testlib. Added test for replugging ISL
  services/src/atdd-staging/pom.xml
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/IslSteps.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/IslMovingSpec.groovy
  services/src/test-library/pom.xml
  services/src/test-library/src/main/java/org/openkilda/testing/config/DefaultServiceConfig.java
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Ready to Merge, area/testing

#1062 #1061: Extend atdd-staging scenario in failsafe suite
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/service/flowmanager/FlowManagerImpl.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/CommonSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/atdd-staging/src/main/resources/features/failsafe_behaviour.feature
Labels: Next Release, area/testing

#1065 Added test for self-loop replug. Stop tests after first failure
  services/src/functional-tests/pom.xml
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/IslMovingSpec.groovy
Labels: Next Release, area/testing

#1072 Lost portion of #1013
  services/src/atdd/src/main/java/org/openkilda/topo/builders/TeTopologyParser.java
  services/src/configuration/pom.xml
  services/src/configuration/src/main/java/org/openkilda/config/KafkaConfig.java
  services/src/configuration/src/main/java/org/openkilda/config/provider/ConfigurationException.java
  services/src/configuration/src/main/java/org/openkilda/config/provider/ValidatingConfigurationProvider.java
  services/src/configuration/src/test/java/org/openkilda/config/provider/ValidatingConfigurationProviderTest.java
  services/src/floodlight-modules/pom.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/config/provider/ConfigurationProvider.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/HeartBeat.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaConsumerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageProducer.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaProducerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationServiceConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsServiceConfig.java
  services/src/pom.xml
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/config/provider/ConfigurationProvider.java
Labels: C/CACHE, C/EVENT, C/FL, C/FLOW, Next Release, Ready to Merge, feature

#1070 Replace '_' to '-' in the names of Kilda services. #976
  base/hacks/usecase/flow.crud.make
  base/hacks/usecase/network.disco.make
  docker-compose.yml
  services/wfm/README.md
Labels: Next Release, Ready to Merge

#1078 Fixing sorted port number issue in add / edit flow
  services/src/openkilda-gui/src/main/resources/ui/js/flows/flowobject.js
Labels: Next Release, Ready to Merge
