Repository telstra/open-kilda, pull requests merged in 2018-05, with the labels that each got.

#708 Fixed issue in graph date (UTC).
  services/src/openkilda-gui/src/main/resources/css/custom.css
  services/src/openkilda-gui/src/main/resources/javascript/common.js
  services/src/openkilda-gui/src/main/resources/javascript/flow-graph-stats.js
  services/src/openkilda-gui/src/main/resources/javascript/flows.js
  services/src/openkilda-gui/src/main/resources/javascript/graph.js
  services/src/openkilda-gui/src/main/resources/javascript/isl-graph-stats.js
  services/src/openkilda-gui/src/main/resources/javascript/isllist.js
  services/src/openkilda-gui/src/main/resources/javascript/switchlist.js
  services/src/openkilda-gui/src/main/resources/templates/flowdetails.html
  services/src/openkilda-gui/src/main/resources/templates/flows.html
  services/src/openkilda-gui/src/main/resources/templates/isl.html
  services/src/openkilda-gui/src/main/resources/templates/isllist.html
  services/src/openkilda-gui/src/main/resources/templates/switchdetails.html
Labels: LGTM, Ready to Release

#750 Hotfix/te issue in relase v1.1.5.7
  services/topology-engine/queue-engine/topologylistener/isl_utils.py
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
  services/topology-engine/queue-engine/topologylistener/tests/test_isl.py
Labels: LGTM, Ready to Release

#745 Separate logger for ISL events in FL
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-modules/src/main/resources/logback.xml
  services/src/floodlight-modules/src/test/resources/logback.xml
  templates/templates/floodlight/logback.xml.j2
Labels: LGTM, Ready to Release

#748 Fix support of loop ISLs in TER /api/v1/topology/routes.
  services/topology-engine-rest/app/app/topology.py
Labels: Ready to Release

#752 Change priority of rules in FL
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/message/command/encapsulation/OutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/message/command/encapsulation/PushSchemeOutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/message/command/encapsulation/ReplaceSchemeOutputCommands.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerOF12Test.java
Labels: LGTM, Ready to Release

#755 Fixed View box height width in topology screen. ->Issue on ISL colour change in auto refresh. ->Added 10 seconds wait on Reroute to get new flow path. Single click on switch node information tooltip appear in topology screen
  services/src/openkilda-gui/src/main/resources/css/custom.css
  services/src/openkilda-gui/src/main/resources/javascript/common.js
  services/src/openkilda-gui/src/main/resources/javascript/flowdetails.js
  services/src/openkilda-gui/src/main/resources/javascript/graph.js
  services/src/openkilda-gui/src/main/resources/templates/topology.html
Labels: LGTM, Ready to Release

#779 Limit neo4j version
  services/neo4j/ansible/deploy.yml
Labels: Ready to Release

#782 Collect excetions in dedicated package
  services/wfm/src/main/java/org/openkilda/simulator/SimulatorTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/AbstractAction.java
  services/wfm/src/main/java/org/openkilda/wfm/CliArguments.java
  services/wfm/src/main/java/org/openkilda/wfm/LaunchEnvironment.java
  services/wfm/src/main/java/org/openkilda/wfm/PropertiesReader.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/CtrlAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/DumpByResorceCacheAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/DumpBySwitchStateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/DumpStateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/ListAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/RouteAction.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/RouteBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/ctrl/RouteMessage.java
  services/wfm/src/main/java/org/openkilda/wfm/error/ConfigurationException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/MessageException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/MessageFormatException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/NameCollisionException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/StreamNameCollisionException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/UnsupportedActionException.java
  services/wfm/src/main/java/org/openkilda/wfm/protocol/BoltToBoltMessage.java
  services/wfm/src/main/java/org/openkilda/wfm/protocol/JsonMessage.java
  services/wfm/src/main/java/org/openkilda/wfm/protocol/KafkaMessage.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/Topology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/TopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFEventWFMTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/PopulateIslFilterAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/islstats/IslStatsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTSDBTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/portstate/PortStateTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/portstate/bolt/TopoDiscoParseBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/portstate/bolt/WfmStatsParseBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/FlowCookieException.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/FlowDirectionHelper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/StatsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/AbstractKafkaParserBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/KafkaFilerTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/KafkaLoggerTopology.java
  services/wfm/src/test/java/org/openkilda/wfm/AbstractStormTest.java
  services/wfm/src/test/java/org/openkilda/wfm/OFEventWfmTest.java
  services/wfm/src/test/java/org/openkilda/wfm/SimpleKafkaTest.java
  services/wfm/src/test/java/org/openkilda/wfm/TestUtils.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/OFELinkBoltTest.java
Labels: C/CACHE, C/EVENT, C/FLOW, C/ISLSTATS, C/OTSDB, C/PORTSTATE, C/STATS, Ready to Release

#780 Fix ISL discovery logger name
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
Labels: C/FL, Ready to Release

#777 Fix error reporting in TE regarding ISL status update
  services/topology-engine/queue-engine/topologylistener/isl_utils.py
Labels: C/TE, Ready to Release

#774 Use lombok on TopologyConfig
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/TopologyConfig.java
Labels: C/CACHE, C/EVENT, C/FLOW, C/ISLSTATS, C/OTSDB, C/PORTSTATE, C/STATS, Ready to Release

#772 Add details into ISL discovery log messages
  services/topology-engine/queue-engine/topologylistener/isl_utils.py
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
  services/topology-engine/queue-engine/topologylistener/model.py
Labels: C/TE, Ready to Release

#765 Deny adding address that collide exising addresses
  services/traffexam/kilda/traffexam/__init__.py
  services/traffexam/kilda/traffexam/exc.py
  services/traffexam/kilda/traffexam/model.py
  services/traffexam/kilda/traffexam/rest.py
  services/traffexam/kilda/traffexam/service.py
Labels: Ready to Release

#791 Log the correlation id as logger MDC in WFM bolts.
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/CliArguments.java
  services/wfm/src/main/java/org/openkilda/wfm/OFEMessageUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/service/CacheWarmingService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/CorrelationContext.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/LoggerContextInitializer.java
  services/wfm/src/main/resources/log4j2.xml
  services/wfm/src/test/resources/log4j2.xml
  templates/templates/storm/log4j2/cluster.xml.j2
  templates/templates/storm/log4j2/worker.xml.j2
Labels: C/CACHE, C/EVENT, C/FLOW, C/ISLSTATS, C/OTSDB, C/PORTSTATE, C/STATS

#792 Cleanup handling of correlationId in Northbound
  services/src/northbound/src/main/java/org/openkilda/northbound/messaging/kafka/KafkaHealthCheckMessageConsumer.java
  services/src/northbound/src/main/java/org/openkilda/northbound/messaging/kafka/KafkaMessageConsumer.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FeatureTogglesServiceImpl.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundBasicAuthenticationEntryPoint.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationFilter.java
  services/src/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationId.java
  services/src/northbound/src/main/resources/log4j2.xml
  services/src/northbound/src/test/java/org/openkilda/northbound/controller/FlowControllerTest.java
  services/src/northbound/src/test/java/org/openkilda/northbound/utils/RequestCorrelationIdTest.java
  services/src/northbound/src/test/resources/log4j2.xml
  templates/templates/northbound/log4j2.xml.j2
Labels: C/NB

#770 Revert remainings of "Add dump_networks endpoint into TPE"
  services/topology-engine-rest/app/app/__init__.py
  services/topology-engine-rest/app/app/network_dump.py
  services/topology-engine-rest/app/wsgi.py
  services/wfm/src/main/java/org/openkilda/wfm/topology/TopologyConfig.java
  templates/templates/wfm/topology.properties.j2
Labels: Ready to Release

#775 Deduplicate flow cache population
  services/src/api/pom.xml
  services/src/atdd-staging/pom.xml
  services/src/atdd/pom.xml
  services/src/messaging/pom.xml
  services/src/messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlow.java
  services/src/pce/pom.xml
  services/src/pce/src/main/java/org/openkilda/pce/provider/AuthNeo4j.java
  services/src/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/FlowCollector.java
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/PathComputerFlowFetcher.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/TopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/StatsTopology.java
Labels: C/CACHE, C/FLOW, Ready to Release

#793 Create service for atdd-staging for management intermediate sw
  services/lock-keeper/Dockerfile
  services/lock-keeper/README.md
  services/lock-keeper/lockkeeper.py
Labels: LGTM, Ready to Release

#801 Introduce support of unmetered flows (with bandwidth = 0)
  services/src/atdd/src/test/resources/features/mvp.1/FlowCrudBasicRun.feature
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/Flow.java
  services/src/pce/src/main/java/org/openkilda/pce/cache/FlowCache.java
  services/src/pce/src/test/java/org/openkilda/pce/cache/FlowCacheTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/CACHE, C/FL, C/FLOW

#800 Send flow stats for ingress switch
  services/wfm/src/checkstyle/checkstyle-header.txt
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/error/JsonEncodeException.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/CacheFlowEntry.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/MeasurePoint.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/bolts/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/bolts/CacheFilterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/metrics/FlowMetricGenBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/metrics/MeterConfigMetricGenBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/metrics/MetricGenBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/metrics/PortMetricGenBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyTest.java
Labels: C/STATS

#766 #720: Fixed issue with moving back an ISL
  services/src/messaging/src/main/java/org/openkilda/messaging/command/discovery/DiscoveryFilterEntity.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/OFELinkBoltState.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslChangeType.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslInfoData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java
  services/topology-engine-rest/app/app/topology.py
  services/topology-engine/queue-engine/topologylistener/isl_utils.py
  services/topology-engine/queue-engine/topologylistener/messageclasses.py
  services/topology-engine/queue-engine/topologylistener/tests/test_isl.py
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/OFEMessageUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DummyIIslFilter.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/IIslFilter.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/OFEventWfmTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryLinkTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryNodeTest.java
Labels: C/EVENT, C/TE, LGTM

#814 Fix bug with single switch flow cache update in stats topology
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/bolts/CacheFilterBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyTest.java
Labels: C/STATS, Ready to Release

#818 #808: Fixed issue with replugging ISL (added temporary storage for re…
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/TopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFELinkBolt.java
  services/wfm/src/main/resources/topology.properties
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
  services/wfm/src/test/resources/topology.properties
  templates/defaults/main.yaml
  templates/templates/wfm/topology.properties.j2
Labels: C/EVENT, Ready to Release

#821 Remove code for change priority disco rules from FL
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
Labels: C/FL, Ready to Release

#819 Allow no javadoc for junit, Cucumber step and Spring configuration methods
  services/src/checkstyle/README.md
  services/src/checkstyle/checkstyle.xml
  services/src/checkstyle/intellij-java-openkilda-style.xml
  services/src/pom.xml
  services/wfm/pom.xml
  services/wfm/src/checkstyle/checkstyle.xml
Labels: LGTM

#831 1.1.5.22 atdd fix
  services/src/atdd-staging/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/DiscoveryMechanismSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/helpers/DefaultFlowsChecker.java
Labels: Ready to Release, area/testing

#812 New ISL or Switch will appear on Auto-refresh in topology screen.
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/IslLinkConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/IslLinkInfo.java
  services/src/openkilda-gui/src/main/resources/css/custom.css
  services/src/openkilda-gui/src/main/resources/javascript/common.js
  services/src/openkilda-gui/src/main/resources/javascript/flows.js
  services/src/openkilda-gui/src/main/resources/javascript/graph.js
  services/src/openkilda-gui/src/main/resources/javascript/isl.js
  services/src/openkilda-gui/src/main/resources/javascript/isllist.js
  services/src/openkilda-gui/src/main/resources/javascript/switchlist.js
  services/src/openkilda-gui/src/main/resources/templates/isl.html
  services/src/openkilda-gui/src/main/resources/templates/topology.html
Labels: C/GUI

#834 #806 Filter non physical port from FL network dump
  services/src/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerMock.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/RecordHandlerTest.java
Labels: C/FL

#832 Remove obsolete LCM flow population mechanism
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRestoreRequest.java
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/cache/CacheTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/StreamType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/SplitterBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/cache/CacheTopologyTest.java
Labels: C/CACHE, C/FLOW, Ready to Release
