Repository telstra/open-kilda, pull requests merged in 2019-10, with the labels that each got.

#2798 Extend Endurance test with a 'break isl' event
  confd/conf.d/perf-tests.kilda_properties.toml
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/HardwareEnvCleanupExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/VirtualEnvCleanupExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/fixture/SetupOnceExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/Dice.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/performance-tests/kilda.properties.example
  services/src/performance-tests/pom.xml
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/model/CustomTopology.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/BaseSpecification.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/DiscoverySpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceV2Spec.groovy
  services/src/performance-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: Ready to Merge, area/testing, improvement

#2833 improve waiting in MflStatSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2840 Fix log message in LinkOperationService.
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/LinkOperationsService.java
Labels: C/NBWORKER, Ready to Merge, bugfix

#2839 add tests for port discovery property
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortPropertiesSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
Labels: Ready to Merge, area/testing, feature

#2837 Moved initialization of connectedDevicesService to setup method
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/connected/ConnectedDevicesService.java
Labels: C/FL, Ready to Merge, area/connected_devices, improvement

#2823 Add notice for autogenerated files
  Makefile
  confd/conf.d/storm.storm_yaml.toml
  confd/templates/atdd-staging/kilda.properties.tmpl
  confd/templates/atdd-staging/log4j2.xml.tmpl
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/templates/floodlight/floodlightkildaStats.properties.tmpl
  confd/templates/floodlight/logback.xml.tmpl
  confd/templates/grpc-service/grpc-service.properties.tmpl
  confd/templates/grpc-service/log4j2.xml.tmpl
  confd/templates/gui/application.properties.tmpl
  confd/templates/gui/logback.xml.tmpl
  confd/templates/logstash/Dockerfile.j2
  confd/templates/logstash/logstash.conf.tmpl
  confd/templates/northbound/log4j2.xml.tmpl
  confd/templates/northbound/northbound.properties.tmpl
  confd/templates/storm/log4j2/cluster.xml.tmpl
  confd/templates/storm/log4j2/worker.xml.tmpl
  confd/templates/storm/storm.yaml.tmpl
  confd/templates/wfm/topology.properties.tmpl
  services/storm/.gitignore
  services/storm/Dockerfile
  services/storm/conf/storm.yaml
Labels: On Review, improvement

#2838 Add perf test for verifying switch validation with a lot of flows
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/BaseSpecification.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/VolumeSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2799 Disable port discovery feature design
  docs/design/network-discovery/disable-port-discovery/README.md
  docs/design/network-discovery/disable-port-discovery/api.yaml
  docs/design/network-discovery/disable-port-discovery/disable-port-discovery.png
  docs/design/network-discovery/disable-port-discovery/disable-port-discovery.puml
  docs/design/network-discovery/disable-port-discovery/domain-model.png
  docs/design/network-discovery/disable-port-discovery/domain-model.puml
  docs/design/network-discovery/port-FSM.png
  docs/design/network-discovery/port-FSM.puml
Labels: Ready to Merge, area/docs

#2836 Delete switch properties when switch is deleted
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
Labels: C/NBWORKER, Ready to Merge, bugfix, tested

#2814 Add disable port discovery feature
  services/neo4j/init/neo4j-queries.cql
  services/neo4j/migrations/1.15-port-properties/1-update-constraints.xml
  services/neo4j/migrations/1.15-port-properties/rollback.cql
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortPropertiesSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/PortProperties.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/PortPropertiesRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jPortPropertiesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jPortPropertiesRepositoryTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/GetPortPropertiesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/UpdatePortPropertiesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/switches/PortPropertiesPayload.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/switches/PortPropertiesDto.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/switches/PortPropertiesResponse.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/SwitchControllerV2.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/PortPropertiesMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/SwitchServiceTest.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/PortMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/IPortCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkPortService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/ComponentId.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/NorthboundEncoder.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/port/PortHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/port/command/UpdatePortPropertiesCommand.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/speaker/SpeakerRouter.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIntegrationCarrier.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIntegrationTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkPortServiceTest.java
Labels: C/NB, C/NBWORKER, C/NETWORK, DB Migration, Ready to Merge, feature, tested

#2842 Fix kafka test config
  services/wfm/src/test/java/org/openkilda/wfm/TestUtils.java
Labels: On Review, area/testing, bugfix

#2850 Replaced oraclejdk8 to openjdk8
  .travis.yml
Labels: On Review, bugfix

#2664 Create SimpleSwitchRule class for switch rules validation.
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/rule/validation/SimpleSwitchRule.java
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/rule/validation/SimpleSwitchRuleConverter.java
  services/wfm/src/test/java/org/openkilda/wfm/share/utils/rule/validation/SimpleSwitchRuleConverterTest.java
Labels: Ready to Merge, improvement

#2841 Allow to use traffexam on python-3.5.2
  services/lab-service/traffexam/kilda/traffexam/__init__.py
  services/lab-service/traffexam/kilda/traffexam/context.py
Labels: Next Release, area/testing, improvement

#2849 Improvement/controller filter default
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/FlowController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/SwitchController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/Flow.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/SwitchIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/FlowInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/FlowControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/SwitchControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/util/TestFlowMock.java
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.ts
  services/src/openkilda-gui/ui/src/app/common/services/flows.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/switch.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-datatables/flow-datatables.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-datatables/flow-datatables.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-graph/flow-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-list/flow-list.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-list/flow-list.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.css
  services/src/openkilda-gui/ui/src/app/modules/switches/flows/flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-graph/port-graph.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-list/port-list.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-list/port-list.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-datatable/switch-datatable.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-datatable/switch-datatable.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-list/switch-list.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-list/switch-list.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: Next Release, improvement

#2863 minor fix in FlowCrudV2Spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2853 Fix exception handling in northbound worker
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortPropertiesSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/PersistenceOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
Labels: C/NBWORKER, Next Release, improvement, refactor

#2866 minor changes in vxlanFlow v1/v2 specs
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#2848 add narrative annotation into SwitchPropertiesSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
Labels: Next Release, area/testing, improvement

#2867 Feature/switch flows
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/SwitchController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/SwitchIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/SwitchControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/util/TestSwitchMock.java
  services/src/openkilda-gui/ui/src/app/app.module.ts
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.ts
  services/src/openkilda-gui/ui/src/app/common/services/switch.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/flows/flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/flows/flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-details/port-details.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.css
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.css
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.css
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.ts
Labels: Ready to Merge, area/gui, feature

#2864 Update jackson lib version
  services/src/atdd-staging/pom.xml
  services/src/functional-tests/pom.xml
  services/src/pom.xml
  services/src/test-library/pom.xml
  services/wfm/pom.xml
Labels: On Review, improvement

#2868 Bumped versions of hbase, kafka, opentsdb, storm and zookeeper
  confd/templates/wfm/topology.properties.tmpl
  services/hbase/Dockerfile
  services/kafka/Dockerfile
  services/kafka/kafka-conf/server.properties
  services/opentsdb/Dockerfile
  services/storm/Dockerfile
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/resources/topology.properties
  services/zookeeper/Dockerfile
Labels: Next Release, area/security, area/storm

#2871 Fixed BFD feature detector
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/BfdFeature.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
Labels: C/FL, On Review, bugfix

#2862 Fix major sonar issues
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/LinkPropertiesSteps.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/ping/PingResponseCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/utils/CorrelationContextTest.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/finder/BestCostAndShortestPathFinder.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/model/Node.java
  services/src/messaging/src/test/java/org/openkilda/messaging/info/flow/FlowStatusResponseTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/pom.xml
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/FlowTrafficExamBuilder.java
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/FlowOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/ping/bolt/ResultDispatcher.java
Labels: On Review, refactor

#2875 Fix db migrations versioning
  services/neo4j/migrations/1.16-multi-table-flag/1-add-multi-table-flag.xml
  services/neo4j/migrations/1.16-multi-table-flag/rollback.cql
Labels: C/NEO4J, On Review, bugfix

#2845 add tests for v1/config API
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Next Release, Ready to Merge, area/testing, feature

#2891 Increase PortHistorySpec stability
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Next Release, area/testing

#2663 Log message if ISL has negative cost
  services/src/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java
Labels: C/FLOW, C/FLOW-HS, Next Release, area/pce, improvement

#2680 Extend network topology dashboard logger
  confd/templates/floodlight/logback.xml.tmpl
  docs/design/network-discovery/ISL-report-FSM.png
  docs/design/network-discovery/ISL-report-FSM.puml
  services/src/floodlight-service/floodlight-modules/pom.xml
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/utils/FloodlightDashboardLogger.java
  services/src/floodlight-service/floodlight-modules/src/main/resources/logback.xml.example
  services/src/kilda-core/kilda-reporting/.gitignore
  services/src/kilda-core/kilda-reporting/pom.xml
  services/src/kilda-core/kilda-reporting/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/kilda-core/kilda-reporting/src/main/java/org/openkilda/reporting/AbstractDashboardLogger.java
  services/src/kilda-core/pom.xml
  services/wfm/pom.xml
  services/wfm/src/main/java/org/openkilda/wfm/share/logger/FlowOperationsDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/AbstractLogWrapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/AntiFlapFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/isl/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/isl/IslReportFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortReportFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/AbstractPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/LogicalBfdPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/PhysicalPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkAntiFlapService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkIslService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIslServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkPortServiceTest.java
Labels: C/FL, C/NETWORK, Next Release, improvement, tested

#2846 add test System does not create a flow when bandwidth is not the same on the ISL
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2854 refactor "System takes isl time_unstable info into account while creating a flow"
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing, improvement

#2880 improve checks for installed rules in vxlanFlowSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2887 Added noviflow virtual switch checks to FeatureDetectorService
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/AbstractFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/NoviFlowCopyFieldFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/PktpsFlagFeature.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
Labels: C/FL, Ready to Merge, bugfix

#2877 Fix minor sonar issues
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/bfd/BfdSessionCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/web/EnableBfdResource.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/share/mappers/FlowMapperTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/FlowServiceTest.java
Labels: C/FL, C/FLOW, Ready to Merge, improvement, refactor
