Repository telstra/open-kilda, pull requests merged in 2019-07, with the labels that each got.

#2549 Fix for swagger correlation id header name
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/SwaggerConfig.java
Labels: C/NB, On Review, bug

#2556 Fix for round trip latency
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/IslPath.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/IslLinkInfo.java
Labels: C/GUI, Ready to Merge, area/gui

#2558 Changed 'isl.latency' to 'isl.rtt' metric in GUI
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.html
Labels: C/GUI, Next Release, area/gui, feature

#2506 Make most traffic examination to run in parallel in both directions
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/traffexam/TraffExamServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/traffexam/networkpool/Inet4NetworkPool.java
Labels: Ready to Merge, area/testing, improvement

#2528 extend FlowDiversitySpec by checking the "diverse_with" field
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2535 [Network topo] Change logging level for port state events.
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkSwitchService.java
Labels: C/NETWORK, Ready to Merge, improvement

#2536 Add API to get all flows for a particular switch or endpoint.
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowPathRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepositoryTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/GetFlowsForSwitchRequest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/SwitchServiceTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/FlowOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
Labels: C/NB, C/NBWORKER, Ready to Merge, area/api, feature

#2544 refactor regex in the grpc spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcCommonSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LicenseSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogicalPortSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2555 Fix occasionally failing SwapEndpoint test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2561 add extra check to prevent fail on a small env
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2564 Add test that reproduces #2563
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2569 Fix flow validation for swap endpoints functionality (for default flows)
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/FLOW, On Review, bug

#2572 Do not use negative round trip latency for OpenTSDB
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/service/IslStatsService.java
Labels: On Review, bug

#2573 Fix validation of switches that don't support meters (FLOW HS topology)
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchFeatures.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ValidateIngressRuleAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/validation/rules/IngressRulesValidator.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/validation/rules/NonIngressRulesValidator.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/validation/rules/RulesValidator.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
Labels: C/FLOW-HS, Next Release, bug

#2577 Fix fsm flow create
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/FlowCreateFsm.java
Labels: C/FLOW-HS, On Review, bug

#2494 add tests for creating 2047 and 4094 flows
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2532 extend ProtectedPathSpec by checking the 'flowStatusDetails' filed
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2539 add test for checking "get all flows for a switch"
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, feature

#2560 Do not ignore Inactive ISLs in latency Cache
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/service/CacheService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/service/CacheServiceTest.java
Labels: C/ISLLATENCY, Ready to Merge, feature

#2567 Changed update latency intervals
  confd/vars/main.yaml
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopologyConfig.java
Labels: Ready to Merge, area/config, improvement

#2570 Add special test that generates topo.yaml based on what is discovered
  services/lab-service/lab/api/api.py
  services/lab-service/lab/service/test/res/topology.json
  services/lab-service/lab/service/topology.py
  services/src/atdd-staging/src/test/resources/3-switch-test-topology.yaml
  services/src/atdd-staging/src/test/resources/5-switch-test-topology.yaml
  services/src/functional-tests/README.md
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/TopologyConfig.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/SpringSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslMinPortSpeedSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/network/PathsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/FloodlightKafkaConnectionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormHeavyLoadSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/special/GenerateTopologyConfig.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/OpenTsdbSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/SimulateStatsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
  services/src/functional-tests/src/test/resources/topology.yaml
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/model/CustomTopology.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
Labels: Ready to Merge, area/testing, improvement

#2476 Do not treat all speaker as unavailable on floodlightrouter start
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/DiscoveryBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/AliveMarker.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/AliveSetup.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/FloodlightTracker.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/MessageSender.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/SpeakerStatus.java
  services/wfm/src/test/java/org/openkilda/wfm/share/utils/ManualClock.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/floodlightrouter/service/FloodlightTrackerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterServiceTest.java
Labels: C/ROUTER, Ready to Merge, improvement

#2553 Fix for vxlan unicast ping rule
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/ping/PingResponseCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/OfFlowStatsMapper.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/ping/PingService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/ping/PingResponseCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/PushSchemeOutputCommands.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Cookie.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/IslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPairRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepositoryTest.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/DeleteRulesAction.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/InstallRulesAction.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/BaseFlowServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java
Labels: C/FL, Ready to Merge, area/vxlan_encapsulation, improvement

#2525 Get rid from event(wfm) topology
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/src/messaging/src/main/java/org/openkilda/messaging/Destination.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/discovery/DiscoveryFilterEntity.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/discovery/DiscoveryFilterPopulateData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/OFELinkBoltState.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/visitor/DumpStateManager.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/visitor/DumpStateVisitor.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/PortChangeType.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/DiscoveryLink.java
  services/wfm/app/Makefile
  services/wfm/src/main/java/org/openkilda/wfm/OfeMessageUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DiscoveryManager.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/DummyIIslFilter.java
  services/wfm/src/main/java/org/openkilda/wfm/isl/IIslFilter.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/NetworkTopologyBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OFEventWfmTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OfEventWfmTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OfeLinkBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/PopulateIslFilterAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/PortEventRouterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/PortEventThrottlingBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/PortEventThrottlingService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/PortService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/Sender.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/SwitchService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/KibanaLogWrapper.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/OfEventWfmTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryLinkTest.java
  services/wfm/src/test/java/org/openkilda/wfm/isl/DiscoveryManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/OutputCollectorMock.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/OfeLinkBoltTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/service/IslServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/service/PortEventThrottlingServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/service/PortServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/service/SwitchServiceTest.java
Labels: C/EVENT, Ready to Merge

#2538 Added feature to display diverse flow path
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/FlowController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/Flow.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowDiversePath.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowDiversePathProtected.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPayload.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowProtectedPath.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/OtherFlows.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/OverlappingSegments.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/FlowsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/FlowControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/util/TestFlowMock.java
  services/src/openkilda-gui/ui/src/app/common/services/common.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/flowpath.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/flows.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.css
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: C/GUI, Ready to Merge, area/gui, feature

#2517 Add logs for port update.
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchTrackingService.java
Labels: C/FL, On Review, enhancement

#2594 add test for a new vxlan default rule/meter
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2589 Minor test updates for better stability
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/SimulateStatsSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2579 add test 'System doesn't allow to create a one-switch flow on a DEACTIVATED switch'
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2604 Revert diverse flow path #2538
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/FlowController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/Flow.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPayload.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/FlowsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/FlowControllerTest.java
  services/src/openkilda-gui/ui/src/app/common/services/common.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/flows.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.css
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: C/GUI, Ready to Merge, area/gui

#2603 Fix flow status of degraded flows w/ or w/o h&s flag
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2607 Disable dumping table stats from OF 1.2
  CHANGELOG.md
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsService.java
Labels: C/FL, Ready to Merge, bug

#2571 Update SwapEndpointSpec with new tests and minor refactoring
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2509 Configurable ping design
  docs/design/hub-and-spoke/ping/configurable-on-demand-pings.md
Labels: On Review, area/arch

#2184 Design for round trip latency
  docs/design/round-trip-latency/current-discovery.puml
  docs/design/round-trip-latency/current_discovery.png
  docs/design/round-trip-latency/generate_packet_structure.sh
  docs/design/round-trip-latency/neo4j_timeline.png
  docs/design/round-trip-latency/new-discovery-not-noviflow.puml
  docs/design/round-trip-latency/new-discovery-noviflow-with-groups-support.puml
  docs/design/round-trip-latency/new_discovery_not_noviflow.png
  docs/design/round-trip-latency/new_discovery_noviflow_with_groups_support.png
  docs/design/round-trip-latency/openstdb_timeline.png
  docs/design/round-trip-latency/round-trip-latency.md
Labels: Ready to Merge, area/arch, area/docs

#2605 Add to FL getting of default rules such as they should be on the switch.
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/OfFlowStatsMapper.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/converter/OfFlowStatsMapperTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/GetExpectedDefaultRulesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/rule/FlowApplyActions.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/rule/FlowCopyFieldAction.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/rule/SwitchExpectedDefaultFlowEntries.java
Labels: C/FL, Next Release, feature

#2606 add new endpoint for managing iptables rules on floodlight
  services/lock-keeper/lockkeeper.py
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/model/InetAddress.java
Labels: Ready to Merge, area/testing, improvement

#2618 Fix one of swap endpoints tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2591 Fix sync rules in case VxLAN encapsulation.
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/service/FlowCommandFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/FlowOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchManagerTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchManagerHub.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/FlowCommandFactoryTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/FlowServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImplTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
Labels: C/FLOW, C/SWMANAGER, Next Release, area/vxlan_encapsulation, feature

#2608 Limit traffexam bandwidth when examing in parallel
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Next Release, area/testing, bug

#2623 Add default rules validation test and update existing validation tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2611 Add the default rules validation in the switch validation.
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/info/rule/FlowEntry.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/switches/RulesValidationEntry.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/switches/RulesValidationDto.java
  services/src/northbound-service/nb-api/src/test/java/org/openkilda/northbound/dto/JsonSerializationTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchManagerHub.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/model/ValidateRulesResult.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/SwitchValidateService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/ValidationService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImplTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImplTest.java
Labels: C/NB, C/ROUTER, C/SWMANAGER, Ready to Merge, feature

#2616 Fixed feature detection for E switches with 500 software
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/AbstractFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/NoviFlowCopyFieldFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/PktpsFlagFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/ResetCountsFlagFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/FeatureDetectorService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SpeakerSwitchView.java
Labels: C/FL, Ready to Merge, bug

#2216 Create FloodlightDashboardLogger for logging OF events
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/OfPortDescConverter.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchTrackingService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/utils/FloodlightDashboardLogger.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/converter/OfPortDescConverterTest.java
Labels: C/FL, Ready to Merge

#2617 add virtualImpl for managing floodlight access
  services/lab-service/lab/service/lockkeeper.py
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/model/InetAddress.java
Labels: Ready to Merge, area/testing, improvement

#2545 Update H&S reroute with encapsulation implementations
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallEgressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallMultiSwitchIngressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallTransitRule.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallEgressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallOneSwitchRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommand.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/InstallIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/InstallNonIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/RollbackInstalledRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocatePrimaryResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocateProtectedResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/InstallIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/InstallNonIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/RemoveOldRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/RevertNewRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/RevertPathsSwapAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/SwapFlowPathsAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowCommandBuilder.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowCommandBuilderFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/TransitBasedFlowCommandBuilder.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/TransitBasedFlowCommandBuilderTest.java
Labels: C/FLOW-HS, Next Release, improvement

#2627 Add workaround to switch validation logic regarding E-switches.
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImplTest.java
Labels: C/SWMANAGER, Ready to Merge, improvement

#2609 Move ExtensionModule file to 'main' to properly resolve in helpers
  services/src/functional-tests/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule
Labels: Ready to Merge, area/testing, bug

#2628 Fix properly picking free port in swap endpoints test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2640 Make flow create retries configurable
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopologyConfig.java
Labels: Next Release, area/config, bug

#2621 inPort and outPort are added as tags for the flow stats
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/OfFlowStatsMapper.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/SimulateStatsSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/info/stats/FlowStatsEntry.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/metrics/FlowMetricGenBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyTest.java
Labels: C/FL, C/STATS, Ready to Merge, feature, tested

#2638 update meterSpec according to wb5164 switch
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Next Release, area/testing, improvement

#2633 Adding feature to update isl bandwidth
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/SwitchController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/SwitchIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/log/constants/ActivityType.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/IslLinkInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/LinkMaxBandwidth.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/src/main/resources/db/import-script_18.sql
  services/src/openkilda-gui/ui/src/app/common/services/isl-list.service.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.ts
Labels: Next Release, area/gui

#2602 Add ContentionSpec for v1 and v2 api
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/Constants.java
Labels: Next Release, area/testing, improvement
