Repository telstra/open-kilda, pull requests merged in 2019-11, with the labels that each got.

#2899 Fix/security issues lodash
  services/src/openkilda-gui/ui/package-lock.json
  services/src/openkilda-gui/ui/package.json
Labels: C/GUI, On Review, Ready to Merge, area/gui, improvement

#2898 Fix flow validation for Centec and E switches.
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Meter.java
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/rule/validation/SimpleSwitchRuleConverter.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/fsm/FlowValidationFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowValidationService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowValidationHubServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowValidationServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowValidationTestBase.java
Labels: C/NBWORKER, Ready to Merge, bugfix

#2901 Fix flow validation for Accton switches.
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/meter/SwitchMeterUnsupported.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SpeakerWorkerBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowValidationHubService.java
Labels: C/FL, C/NBWORKER, Next Release, bugfix

#2902 Renamed org.openkilda.converter package
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/converters/DetectConnectedDevicesConverterTest.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/converters/SwitchFeatureConverterTest.java
Labels: C/FL, Ready to Merge, improvement

#2908 Fix incorrect output port for single-switch-single-port flows
  CHANGELOG.md
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallOneSwitchRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/FlowCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallOneSwitchRuleCommandTest.java
Labels: C/FL, On Review, bugfix

#2896 Add stability hotfixes and temporary ignore some tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2919 Fix flow ping ethernet header
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/vars/main.yaml
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannel.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KildaCore.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KildaCoreConfig.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/ping/PingService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/resources/floodlightkilda.properties.example
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/ping/PingCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/ping/PingServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge, bugfix

#2915 Make http async timeout for nb configurable
  confd/templates/northbound/northbound.properties.tmpl
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/WebConfig.java
  services/src/northbound-service/northbound/src/main/resources/northbound.properties.example
  services/src/northbound-service/northbound/src/test/resources/northbound.properties
Labels: C/NB, Ready to Merge, improvement

#2895 Update design doc for PCE
  docs/design/path-computation.md
  docs/design/pce/design.md
  docs/design/solutions/pce-weights-strategies/pce-weights-strategies.md
  docs/design/solutions/pce-weights-strategies/pce-weights-strategies.png
  docs/design/solutions/pce-weights-strategies/pce-weights-strategies.puml
Labels: Ready to Merge, area/docs

#2870 Remove outdated code
  services/wfm/src/test/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopologyTest.java
Labels: Ready to Merge, area/testing

#2922 Fix OOM in Neo4jPersistenceManager caused by ClassGraph
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/Neo4jPersistenceManager.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/SimpleConversionCallback.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/SimpleConversionCallbackTest.java
Labels: C/FLOW, C/FLOW-HS, C/NBWORKER, C/NETWORK, C/REROUTE, C/SWMANAGER, On Review, area/persistence, improvement

#2913 Adding improvement in topology screen to icon menu
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-search/flow-search.component.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/topology-menu/topology-menu.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/topology-menu/topology-menu.component.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/topology.component.ts
  services/src/openkilda-gui/ui/src/assets/images/18x18/import-export.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/import-export.png
  services/src/openkilda-gui/ui/src/assets/images/up-down-black.png
  services/src/openkilda-gui/ui/src/assets/images/up-down-grey.png
  services/src/openkilda-gui/ui/src/styles.css
Labels: C/GUI, Ready to Merge, area/gui

#2930 improve SwitchPropertiesSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2931 Fix stability of SwitchPropertiesSpec
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/Constants.java
Labels: Ready to Merge, area/testing, bugfix

#2938 add negative tests for multiTable
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
Labels: On Review, area/testing, improvement

#2939 Temporary disable changing of `enable_bfd` flag
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
Labels: C/NB, Next Release, improvement

#2940 improve checking of the lastUpdated field
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2903 check that system doesn't ignore encapsulationType when ignoreBandwidth=true
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2872 improve portHistoryspec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Next Release, area/testing, improvement

#2920 Mark v1 specs that have v2 alternative as low priority
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceV2Spec.groovy
Labels: Ready to Merge, area/testing

#2950 minor improve in flowCrud specs
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2944 Allow some tests to be marked as those with perfect cleanup
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/failfast/FailFastExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/failfast/Tidy.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowConnectedDeviceSpec.groovy
Labels: Next Release, area/testing, improvement

#2936 Improve switch properties validation
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/error/IllegalSwitchPropertiesException.java
  services/wfm/src/main/java/org/openkilda/wfm/error/SwitchPropertiesNotFoundException.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsServiceTest.java
Labels: C/NB, C/NBWORKER, Next Release, bugfix

#2942 Define disruptor configuration for local environment
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/AbstractTopologyConfig.java
  services/wfm/src/main/resources/topology.properties.example
Labels: C/CONNECTED, C/FLOW, C/FLOW-HS, C/NBWORKER, C/NETWORK, C/PING, C/REROUTE, C/SWMANAGER, Next Release, area/config, area/performance, improvement

#2923 PCE bug fix
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/IslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/AvailableNetworkFactoryTest.java
Labels: C/FLOW, C/FLOW-HS, C/NBWORKER, Next Release, area/pce, bugfix

#2953 improve swapEndpointSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Next Release, area/testing, improvement

#2959 Added envs for regions and roles for FL log files in JSON
  confd/templates/floodlight/logback.xml.tmpl
Labels: Next Release, area/config, improvement

#2970 Minor test updates related to V2 migration
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
Labels: Ready to Merge, area/testing

#2965 Minor stability tweaks in functional tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/FloodlightKafkaConnectionSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2835 Update some configuration for local setup to speed up test execution
  confd/vars/main.yaml
  services/src/functional-tests/README.md
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Ready to Merge, area/config, area/docs, area/testing, improvement

#2973 Minor stability fixes in functional tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: On Review, area/testing, improvement

#2818 Add Server 42 Design
  docs/design/server42/README.md
  docs/design/server42/cp.png
  docs/design/server42/cp.puml
  docs/design/server42/dep.puml
  docs/design/server42/packet_process.png
  docs/design/server42/packet_process.puml
  docs/design/server42/server42dep.png
  docs/design/server42/src/server42_mk3/CMakeLists.txt
  docs/design/server42/src/server42_mk3/build_debug.sh
  docs/design/server42/src/server42_mk3/build_release.sh
  docs/design/server42/src/server42_mk3/include/server42/EchoThread.h
  docs/design/server42/src/server42_mk3/include/server42/FlowPool.h
  docs/design/server42/src/server42_mk3/include/server42/Payload.h
  docs/design/server42/src/server42_mk3/include/server42/ProcessThread.h
  docs/design/server42/src/server42_mk3/include/server42/ReadThread.h
  docs/design/server42/src/server42_mk3/include/server42/WriteThread.h
  docs/design/server42/src/server42_mk3/include/server42/control.proto
  docs/design/server42/src/server42_mk3/include/server42/statistics.proto
  docs/design/server42/src/server42_mk3/install_requirements.sh
  docs/design/server42/src/server42_mk3/src/DpdkDeviceList.cpp.patch01
  docs/design/server42/src/server42_mk3/src/EchoThread.cpp
  docs/design/server42/src/server42_mk3/src/FlowPoolTest.cpp
  docs/design/server42/src/server42_mk3/src/ProcessThread.cpp
  docs/design/server42/src/server42_mk3/src/ReadThread.cpp
  docs/design/server42/src/server42_mk3/src/WriteThread.cpp
  docs/design/server42/src/server42_mk3/src/echo-server42.cpp
  docs/design/server42/src/server42_mk3/src/server42.cpp
Labels: Ready to Merge, area/api, area/arch, area/docs, area/performance, area/stats, feature, scale

#2900 add tests for multiTable feature
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowConnectedDeviceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableSwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MultiTableRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/Constants.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, feature

#2929 Feature/flow diversity and network path
  services/src/openkilda-gui/pom.xml
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/CommonRequestHandlerController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/NetworkController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/converter/FlowPathConverter.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/Flow.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowDiversePath.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/model/response/FlowPayload.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/FlowsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/NetworkIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/FlowInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/NetworkPathInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/Node.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/Path.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/NetworkService.java
  services/src/openkilda-gui/ui/src/app/app-routing.module.ts
  services/src/openkilda-gui/ui/src/app/app.module.ts
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.css
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.html
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.ts
  services/src/openkilda-gui/ui/src/app/common/services/flowpath.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/switch.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path/flow-path.component.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/networkpath/networkpath.component.css
  services/src/openkilda-gui/ui/src/app/modules/networkpath/networkpath.component.html
  services/src/openkilda-gui/ui/src/app/modules/networkpath/networkpath.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/networkpath/networkpath.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-flows/port-flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/port-inventory-flows/port-inventory-flows.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-flows/switch-flows.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: Ready to Merge, area/gui

#2974 Handles reroute failures caused by over-provisioning
  confd/templates/wfm/topology.properties.tmpl
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/FlowRerouteHubBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/FlowUpdateHubBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/BaseResourceAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocatePrimaryResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocateProtectedResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/FlowUpdateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/actions/AllocatePrimaryResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/actions/AllocateProtectedResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowUpdateService.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/AbstractFlowTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowUpdateServiceTest.java
Labels: C/FLOW-HS, Ready to Merge, bugfix

#2978 Fix stability of port history test
  services/src/functional-tests/pom.xml
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PortAntiflapHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/PortHistoryEvent.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2979 Ignore port stats test as being unstable
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Ready to Merge, area/testing

#2826 Extend local execution time for storm topologies
  confd/templates/wfm/topology.properties.tmpl
  services/wfm/src/main/resources/topology.properties.example
Labels: On Review, area/storm, improvement

#2967 Improve error handling and logging in H&S FSMs
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/exception/FlowProcessingException.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/BaseFlowPathRemovalAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/BaseResourceAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/FlowProcessingAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/HistoryRecordingAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/NbTrackableAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/CompleteFlowCreateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesDeallocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/delete/actions/ValidateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/actions/RevertFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/actions/UpdateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/update/actions/ValidateFlowAction.java
Labels: C/FLOW-HS, Ready to Merge, improvement

#2964 Fix for parse error in switch props update
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
Labels: C/NBWORKER, Ready to Merge, bugfix

#2945 Valdate Switch Props against supported features
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/JacksonMixinExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchProperties.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/model/SwitchPropertiesTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
Labels: C/NBWORKER, On Review, area/multi_table_pipeline, area/vxlan_encapsulation, improvement

#2963 Fix for single switch flow
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImplTest.java
Labels: C/SWMANAGER, On Review, bugfix, tested
