Repository telstra/open-kilda, pull requests merged in 2019-08, with the labels that each got.

#2493 Repeat db transation on db locks
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/TransactionManager.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/Neo4jTransactionManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/model/NetworkOptions.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkSwitchService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/sw/SwitchHandler.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/AbstractFlowTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIntegrationTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIslServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkSwitchServiceTest.java
Labels: C/NEO4J, C/NETWORK, Ready to Merge, improvement

#2657 fix pinned flow spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2631 Get rid of kafka breaker
  base/kilda-base-ubuntu/Dockerfile
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/templates/floodlight/floodlightkildaStats.properties.tmpl
  docker-compose.yml
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannel.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannelConfig.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageCollector.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/TestAwareConsumer.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/KafkaProducerProxy.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/KafkaUtilityService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/TestAwareKafkaProducerService.java
  services/src/floodlight-service/floodlight-modules/src/main/resources/floodlightkildaStats.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/HardwareEnvCleanupExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/VirtualEnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/FloodlightKafkaConnectionSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/KafkaBreakTarget.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/KafkaBreakTrigger.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/KafkaBreakerAction.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/kafka/KafkaBreakException.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/kafka/KafkaBreaker.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/kafka/KafkaBreakerImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
Labels: Ready to Merge, area/testing, improvement

#2516 add tests for checking the encapsulation-type field
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
Labels: Next Release, area/testing, improvement

#2612 add tests for pinned/protected/diverse/default flow via APIv2
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2645 Fix for installing meter for vxlan unicast
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
Labels: C/FL, Next Release, On Review, area/vxlan_encapsulation, bug

#2655 Added go to table instruction to OF flow mapping
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/OfFlowStatsMapper.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/converter/OfFlowStatsMapperTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/rule/FlowInstructions.java
Labels: C/FL, Next Release, bug, tested

#2654 Refactor unit tests for install default rules
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
Labels: C/FL, Next Release, area/testing, improvement, refactor

#2626 test: "System recreates excess meter when flow is created with the same meterId"
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
Labels: Next Release, area/testing, improvement

#2649 Fix: Ignore default rules when sync rules.
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
Labels: C/SWMANAGER, Next Release, Ready to Merge, bug, tested

#2646 Add WB5164 support to tests as well as various misc fixes
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/fixture/SetupOnceExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/spring/SpringContextExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/tools/FlowTrafficExamBuilder.java
Labels: Next Release, area/testing, improvement

#2667 Added condition to skip cost reduction when link goes from state under maintenance and cost less than isl.cost.when.under.maintenance.
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/LinkOperationsService.java
Labels: C/NBWORKER, Next Release, bug

#2601 Introduce a custom dashboard logger for flow operations.
  services/wfm/src/main/java/org/openkilda/wfm/share/logger/FlowOperationsDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/BaseFlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/FlowCreateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/CompleteFlowCreateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/FlowValidateAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/HandleNotCreatedFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocateProtectedResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnNoPathFoundAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/UpdateFlowStatusAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
Labels: C/FLOW, C/FLOW-HS, C/NBWORKER, C/REROUTE, Next Release

#2666 Fix flow create retries
  services/src/messaging/src/main/java/org/openkilda/messaging/info/flow/FlowReadResponse.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v1/TestMessageMock.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/model/FlowData.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/BaseFlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/SpeakerCommandFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/FlowCreateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/HandleNotCreatedFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesDeallocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
Labels: C/FLOW-HS, Ready to Merge, bug

#2670 Fix flows in DOWN state without flow paths
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/model/FlowWithFlowPaths.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/model/ReroutedFlowPaths.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/BaseFlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java
Labels: C/FLOW, C/NB, C/NBWORKER, Ready to Merge, bug

#2674 Introduce FlowOperations Kibana dashboard
  services/wfm/src/main/java/org/openkilda/wfm/share/logger/FlowOperationsDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocatePrimaryResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/AllocateProtectedResourcesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/BaseResourceAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/PostResourceAllocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/UpdateFlowStatusAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
  tools/elk-dashboards/dashboard/db_b6a75a70-42cd-11e8-8a3b-03954453f1cc.json
  tools/elk-dashboards/search/search_1fb3d0f0-425d-11e8-86e2-f5620c719589.json
  tools/elk-dashboards/search/search_4c213750-42b1-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/search/search_5cb3ee60-f16b-11e7-a202-e79f0134df49.json
  tools/elk-dashboards/search/search_88dffe30-42cd-11e8-8a3b-03954453f1cc.json
  tools/elk-dashboards/search/search_f687aab4-ca7c-4a2f-a49f-f8f49a3f5d67.json
  tools/elk-dashboards/visualization/vis_03da69c0-42cb-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/visualization/vis_03f97be2-f7f7-46f5-947a-cc187a5b578a.json
  tools/elk-dashboards/visualization/vis_1527faf0-3bf8-11e8-a58d-b1da056b2e80.json
  tools/elk-dashboards/visualization/vis_238bd33f-0f41-4158-88e0-b81749ae7ff2.json
  tools/elk-dashboards/visualization/vis_378dcee0-42be-11e8-a33d-e7df8e48ccb6.json
  tools/elk-dashboards/visualization/vis_8e63d120-3bf6-11e8-916f-3fb185ebad8c.json
  tools/elk-dashboards/visualization/vis_abfbc9a3-c974-4d6c-831c-ac0f5d0f9902.json
  tools/elk-dashboards/visualization/vis_b9dbc3c0-42c8-11e8-a33d-e7df8e48ccb6.json
Labels: C/FLOW, C/FLOW-HS, On Review

#2677 Fix error code for flow validation if flow is in DOWN state
  docs/guidelines/api-guidelines.md
  services/src/messaging/src/main/java/org/openkilda/messaging/error/ErrorType.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
Labels: C/NB, Ready to Merge, bug

#2678 Fix failed flow creation/reroute without paths
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesDeallocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnNoPathFoundAction.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
Labels: C/FLOW-HS, On Review, bug

#2637 Enable Vxlan support for v2 api
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallEgressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallTransitRule.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowRemoveCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallEgressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallEgressRuleCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommandTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/TransitBasedFlowCommandBuilder.java
Labels: C/FL, Ready to Merge, area/vxlan_encapsulation, tested

#2683 Fix Kilda-FlowOperations-Filtered-Table Kibana search
  tools/elk-dashboards/search/search_88dffe30-42cd-11e8-8a3b-03954453f1cc.json
Labels: Ready to Merge, area/ops

#2672 Misc fixes in tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/Tag.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2685 Fix default flow creation in v2 +fixed resetting of FSM in case of retry
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/flows/FlowEndpointV2.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/FlowCreateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/OnReceivedInstallResponseAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ResourcesDeallocationAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ValidateIngressRuleAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ValidateNonIngressRuleAction.java
Labels: C/FLOW-HS, C/NB, On Review, bug

#2662 Fixed incorrect converting meter rate/burstsize from packets to kilobits
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Meter.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/model/MeterTest.java
Labels: C/FL, Ready to Merge, area/connected_devices, bug

#2691 Increase wait after wfm finished for better test stability.
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/WfmManipulator.groovy
Labels: Ready to Merge, area/testing, improvement

#2647 add tests: vxlan for api v2
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#2673 Simplify unit test exec process
  Makefile
Labels: Ready to Merge, improvement

#2669 Added models and repos for Connected Devices
  services/neo4j/init/neo4j-queries.cql
  services/neo4j/migrations/1.9-connected-devices/1-update-constraints-changelog.xml
  services/neo4j/migrations/1.9-connected-devices/rollback.cql
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/ConnectedDevice.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/FlowMeter.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/LldpResources.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/ConnectedDeviceRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowMeterRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/LldpResourcesRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jConnectedDevicesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowMeterRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jLldpResourcesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jConnectedDeviceRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowMeterRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jLldpResourcesRepositoryTest.java
Labels: C/NEO4J, Ready to Merge, area/connected_devices, feature

#2686 Add the default rules to switch rules synchronization.
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/ReinstallDefaultFlowForSwitchManagerRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/InstallRulesAction.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/flow/FlowReinstallResponse.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/switches/RulesSyncEntry.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/switches/RulesSyncDto.java
  services/src/northbound-service/nb-api/src/test/java/org/openkilda/northbound/dto/JsonSerializationTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/SwitchServiceTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterUtils.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchManagerHub.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/SwitchSyncService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
Labels: C/FL, C/SWMANAGER, Ready to Merge, improvement

#2596 Added udp dst port match into broadcast default rule.
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge, bug

#2700 Update tests to workaround issue #2595
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/Constants.java
Labels: Ready to Merge, area/testing, bug

#2695 Fix flow delete without resources +flow reroute v2 resource deallocation
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/RouterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/CompleteFlowPathRemovalAction.java
Labels: C/FLOW, C/FLOW-HS, Ready to Merge, bug

#2668 Use hs auto-reroutes by default. Update waiters for path allocation
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/Constants.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/RouterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/CompleteFlowPathRemovalAction.java
Labels: Next Release, area/testing, improvement

#2705 Hot fix wrong error message expected in func tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2710 Do not match UDP port for broadcast rule on Centec
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/MatchUdpPortFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/FeatureDetectorService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchFeature.java
Labels: C/FL, Next Release, bug

#2644 Add multitable flag for fl commands
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/GetInstalledRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallEgressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallFlowRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallIngressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallMeteredRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallMultiSwitchIngressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallSingleSwitchIngressRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/InstallTransitRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/RemoveRule.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/request/SpeakerFlowRequest.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowInstallCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowRemoveCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/GetRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallEgressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallOneSwitchRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommand.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallEgressRuleCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallIngressRuleCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/InstallTransitRuleCommandTest.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/BaseInstallFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallEgressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallIngressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallOneSwitchFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallTransitFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/RemoveFlow.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/BaseInstallFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallEgressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallIngressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallOneSwitchFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallTransitFlowTest.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/service/FlowCommandFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/DumpIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/DumpNonIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/DumpIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/DumpNonIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/TransitBasedFlowCommandBuilder.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/transactions/FlowCommandRegistryTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
Labels: On Review, area/multi_table_pipeline, area/vxlan_encapsulation, feature

#2675 Get rid from ISL cost manipulation in DB.
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Isl.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/IslConfig.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/model/IslTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/Neo4jPersistenceManager.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/NetworkConfig.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/spi/Neo4jPersistenceProvider.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/Neo4jBasedTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/Neo4jTxConcurrencyTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepositoryTest.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/model/Edge.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/finder/BestCostAndShortestPathFinderTest.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/impl/AvailableNetworkTest.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/impl/InMemoryPathComputerTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/NbWorkerTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/NbWorkerTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/LinkOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/model/NetworkOptions.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/bolts/LinkOperationsBoltTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/LinkOperationsServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIntegrationTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIslServiceTest.java
  services/wfm/src/test/resources/topology.properties
Labels: C/NETWORK, Ready to Merge, improvement, tested

#2715 Fixed RemoveFlow constructor error
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
Labels: C/FL, Ready to Merge

#2722 Add missing flow reroute fail event in flow dashboard
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, Next Release

#2724 Add retry when neo4j's ClientException is thrown
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, Ready to Merge, bugfix

#2720 Take into account bugfix label while generating changelog
  tools/changelog-generator/changelog-generator.py
Labels: Ready to Merge

#2711 Add 'purgeTopology' setup step in performance tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/special/GenerateTopologyConfig.groovy
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#2687 refactor flowHelperV2,flowCrud,swapEndpoint files
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2721 Fix CommandBuilder in the SwitchManager topology.
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImplTest.java
Labels: C/SWMANAGER, Ready to Merge, bugfix

#2723 add "See" annotation
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2653 extend vxlanFlow tests (APIv1) by checking rules
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2713 Adjust all tests to properly handle antiflap cooldown.
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PortAntiflapHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/FloodlightKafkaConnectionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2566 Minor change for which tests are tagged as SMOKE_SWITCHES
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/HealthCheckSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/OpenTsdbSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2712 Fix switch rules synchronization.
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImplTest.java
Labels: C/SWMANAGER, Next Release, bugfix, tested

#2728 small improvements for tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
Labels: Next Release, area/testing, improvement

#2730 Fix tag extension for cases when no IterationTags annotation present
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
Labels: Next Release, area/testing, bugfix

#2732 adjust flowCrud to work with not empty env
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Next Release, area/testing, improvement

#2727 Split consumer groups for different regions
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  docker-compose.yml
Labels: C/FL, Next Release, area/floodlight, area/high-availability, tested

#2679 Expose switch features over rest api
  services/neo4j/init/neo4j-queries.cql
  services/neo4j/migrations/1.10-switch-properties/1-rename-switch-features-changelog.xml
  services/neo4j/migrations/1.10-switch-properties/rollback.cql
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchProperties.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/SwitchPropertiesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchPropertiesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/Neo4jBasedTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4JSwitchPropertiesRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepositoryTest.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/impl/InMemoryPathComputerTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SwitchPropertiesDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/GetSwitchPropertiesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/UpdateSwitchPropertiesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchPropertiesResponse.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/switches/SwitchPropertiesDto.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/KildaConfigurationController.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/SwitchMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/create/action/ValidateIngressRuleAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/validation/rules/IngressRulesValidator.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkSwitchServiceTest.java
Labels: C/NB, C/NBWORKER, C/NEO4J, DB Migration, Next Release, tested

#2690 Switch Validation Refactoring
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchManagerTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchManagerHub.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/model/SimpleMeterEntry.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/SwitchManagerCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/ValidationService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImplTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImplTest.java
Labels: C/SWMANAGER, Next Release, area/connected_devices, improvement

#2741 small improvements for tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
Labels: Next Release, area/testing, improvement

#2671 Produce LLDP packets by traffexam
  services/lab-service/lab/api/api.py
  services/lab-service/traffexam/kilda/traffexam/__init__.py
  services/lab-service/traffexam/kilda/traffexam/action.py
  services/lab-service/traffexam/kilda/traffexam/context.py
  services/lab-service/traffexam/kilda/traffexam/core.py
  services/lab-service/traffexam/kilda/traffexam/exc.py
  services/lab-service/traffexam/kilda/traffexam/model.py
  services/lab-service/traffexam/kilda/traffexam/rest.py
  services/lab-service/traffexam/kilda/traffexam/system.py
  services/lab-service/traffexam/requirements.txt
Labels: Next Release, improvement

#2735 add tests for the port history feature
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
Labels: Ready to Merge, area/testing, improvement
