Repository telstra/open-kilda, pull requests merged in 2019-03, with the labels that each got.

#2048 ADD test: Try to sync meters for unmetered flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Ready to Merge, area/testing

#2057 Added prefix for open-kilda gui application name for 2FA
  confd/templates/gui/application.properties.tmpl
  confd/vars/main.yaml
Labels: C/GUI, Ready to Merge, area/gui

#2097 Refactoring of functional tests and small cleanup
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/IslSteps.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/VirtualEnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenance.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Next Release, area/testing

#2105 Revert resetCosts() implementation to directly run cypher query
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing

#2100 Add "time_create" field to the flow object.
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/helpers/FlowSet.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowCrudSteps.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/FlowPair.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowCreatePayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowUpdatePayload.java
  services/src/northbound/src/test/java/org/openkilda/northbound/controller/TestMessageMock.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, Ready to Merge

#2102 #2101 Fix of logging errors during rules synchronization.
  services/wfm/src/main/java/org/openkilda/wfm/share/hubandspoke/CoordinatorBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchSyncRulesManager.java
  services/wfm/src/test/java/org/openkilda/wfm/share/hubandspoke/CoordinatorBoltTest.java
Labels: Next Release, epic/hub@spoke

#2021 Add usage minimal port speed for ISL when have different port speed
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketSignTest.java
Labels: C/FL, Ready to Merge

#2124 Add additional meter validation functional test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Ready to Merge, area/testing

#1689 Virtual OF meters support (OVS 2.10)
  Makefile
  README.md
  base/kilda-base-lab-service/Dockerfile
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  services/lab-service/Dockerfile
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManagerConfig.java
  services/src/floodlight-modules/src/main/resources/floodlightkilda.properties.example
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
Labels: C/FL, Ready to Merge, area/testing

#2079 #2065 Disable flow rerouting when one of the flow endpoints goes to the "down" state.
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
Labels: Ready to Merge

#2091 2076: Add cleanup extension for hardware env
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/exception/IslNotFoundException.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/EnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/HardwareEnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/VirtualEnvCleanupExtension.groovy
  services/src/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
  services/src/test-library/src/main/java/org/openkilda/testing/config/DefaultServiceConfig.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing

#2096 Extend/fix functional tests for meters
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Ready to Merge, area/testing

#2111 Refactor and fix atdd-staging
  services/src/atdd-staging/.gitignore
  services/src/atdd-staging/README.md
  services/src/atdd-staging/kilda.properties.example
  services/src/atdd-staging/log4j2.xml.example
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/helpers/DefaultFlowsChecker.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/helpers/FlowSet.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/CleanupSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/CommonSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/DiscoveryMechanismSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/HealthCheckSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/IslSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/LinkPropertiesSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/LinkSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/NorthboundSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/SwitchSteps.java
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/TopologyVerificationSteps.java
  services/src/atdd-staging/src/main/resources/cucumber.properties
  services/src/atdd-staging/src/main/resources/cucumber.xml
  services/src/atdd-staging/src/main/resources/features/discovery_mechanism.feature
  services/src/atdd-staging/src/main/resources/features/failsafe_behaviour.feature
  services/src/atdd-staging/src/main/resources/features/flow_crud.feature
  services/src/atdd-staging/src/main/resources/features/northbound_smoke.feature
  services/src/atdd-staging/src/test/resources/cucumber.properties
Labels: Ready to Merge, area/testing

#2114 AvailableNetwork reducing with diversity weights
  services/src/kilda-pce/src/main/java/org/openkilda/pce/finder/BestCostAndShortestPathFinder.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/model/Edge.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/model/Node.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/impl/AvailableNetworkTest.java
Labels: Ready to Merge, area/pce

#2115 Fix ISL packet loss graph issues for DPS and forward/reverse direction
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/StatsIntegrationService.java
  services/src/openkilda-gui/ui/src/app/common/dygraph/dygraph.component.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.ts
Labels: C/GUI, Ready to Merge

#2118 1345: Added test that reproduces link oversubscribe issue
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
Labels: Ready to Merge, area/testing

#2121 Fix functional test for verifying proper diverse flow path computation
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
Labels: Ready to Merge, area/testing

#2125 Issue 2045: Fixed incorrect flow count in delete switch error message
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
Labels: C/NBWORKER, Ready to Merge, area/testing

#2129 #2123 Fix flow mappers.
  services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
Labels: C/NB, Ready to Merge

#2108 #2088 Add logic for priority flow rerouting.
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/RerouteTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/RerouteTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/FlowThrottlingBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/RerouteBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/model/FlowThrottlingData.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/ExtendableTimeWindow.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/ReroutesThrottling.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/reroute/service/ReroutesThrottlingTest.java
Labels: Ready to Merge

#2130 Make database interface in test library consistent
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/EnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing

#2122 #1630 Make OpenTSDB metric prefix configurable.
  confd/templates/gui/application.properties.tmpl
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/StatsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/StatsService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/utility/ApplicationProperties.java
  services/src/openkilda-gui/src/main/resources/application.properties.example
  services/src/openkilda-gui/ui/src/app/common/services/dygraph.service.ts
Labels: C/GUI, Ready to Merge

#2092 Add test to verify flow is not rerouted when flow port goes down
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
Labels: Ready to Merge, area/testing

#2133 Fix functional tests for #1640
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
Labels: area/testing

#2136 Fix for missing dps issue in stats graph
  services/src/openkilda-gui/ui/src/app/common/dygraph/dygraph.component.ts
  services/src/openkilda-gui/ui/src/app/common/services/dygraph.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-list/flow-list.component.ts
Labels: Next Release, Ready to Merge, area/gui

#2147 Fix for read value of OpenTSDB metric prefix from property file
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
Labels: C/GUI, Ready to Merge

#2157 Enhancement/Filter on switch list and flow list for controller and inventory data
  services/src/openkilda-gui/src/main/java/org/openkilda/model/FlowInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/model/SwitchInfo.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/FlowService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-datatables/flow-datatables.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-datatables/flow-datatables.component.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/datatable/datatable.component.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-list/isl-list.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-datatable/switch-datatable.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-datatable/switch-datatable.component.ts
  services/src/openkilda-gui/ui/src/app/modules/usermanagement/permissions/permission-list/permission-list.component.ts
  services/src/openkilda-gui/ui/src/app/modules/usermanagement/roles/role-list/role-list.component.ts
  services/src/openkilda-gui/ui/src/app/modules/usermanagement/users/user-list/user-list.component.ts
Labels: Ready to Merge, area/gui

#2150 #2149 Fix flow created time.
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, Ready to Merge

#2148 Fix atdd-staging tests
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowSteps.java
Labels: Next Release, Ready to Merge, area/testing

#2126 Issue 2027: fixed response code for nonexistent flow validation
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/northbound/src/main/java/org/openkilda/northbound/service/FlowService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
Labels: C/NB, Ready to Merge, area/api, area/testing

#1992 POC for storm-decouple
  docs/design/storm-decouple/poc/pom.xml
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/DecisionMakerService.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/IDecisionMakerCarrier.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/IWatchListServiceCarrier.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/IWatcherServiceCarrier.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/SwitchId.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/WatchListService.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/WatcherService.java
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/seq.png
  docs/design/storm-decouple/poc/src/main/java/org/openkilda/seq.puml
  docs/design/storm-decouple/poc/src/test/java/org/openkilda/DecisionMakerServiceTest.java
  docs/design/storm-decouple/poc/src/test/java/org/openkilda/IntegrationTest.java
  docs/design/storm-decouple/poc/src/test/java/org/openkilda/WatchListServiceTest.java
  docs/design/storm-decouple/poc/src/test/java/org/openkilda/WatcherServiceTest.java
Labels: Ready to Merge, area/docs

#2156 Fix cleanup extension for hardware env
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/env/EnvCleanupExtension.groovy
Labels: Ready to Merge, area/testing

#2022 Update virtual topology to look similar to staging. Add parallel ISLs
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/resources/topology.yaml
Labels: Ready to Merge, area/testing

#2069 Restore correlation id in discovery packet events
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/command/CommandWrapper.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/service/CommandProcessorService.java
Labels: C/FL, Ready to Merge

#1971 Add error messages for conflicts on create flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
Labels: C/FLOW, Ready to Merge

#2117 ADD: HistoryNB tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistorySpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing

#2143 Extend link connectivity test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/event/service/IslServiceTest.java
Labels: Ready to Merge, area/testing

#2164 Enable floodlight router for stats topic
  services/src/configuration/src/main/java/org/openkilda/config/KafkaTopicsConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/portstate/PortStateTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/StatsTopologyConfig.java
Labels: C/PORTSTATE, C/STATS, Ready to Merge, epic/multi-floodlight

#2166 Make GRPC kafka config configurable
  .gitignore
  confd/templates/grpc-service/grpc-service.properties.tmpl
  confd/vars/main.yaml
  services/src/grpc-speaker/grpc-service/src/main/resources/grpc-service.properties.example
Labels: C/GRPC, area/config

#2165 Minor fixes around tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormHeavyLoadSpec.groovy
Labels: Ready to Merge, area/testing

#2141 Refactor flow reroute throttling tests
  services/wfm/src/test/java/org/openkilda/wfm/topology/reroute/service/ReroutesThrottlingTest.java
Labels: Ready to Merge, area/testing

#2168 Minor fixes around tests - part 2
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
Labels: Ready to Merge, area/testing

#2172 Remove FL dependency from Configuration component.
  services/src/configuration/pom.xml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Meter.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
Labels: C/FL, C/SWMANAGER, Ready to Merge

#2159 Stabilize CheckLoggingSpec test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy
Labels: Ready to Merge, area/testing

#2086 Fixed GET /network/paths API
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/network/PathsSpec.groovy
  services/src/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/network/Path.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/network/PathsInfoData.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/PathNodePayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/network/PathDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/network/PathsDto.java
  services/src/northbound/src/main/java/org/openkilda/northbound/controller/NetworkController.java
  services/src/northbound/src/main/java/org/openkilda/northbound/converter/PathMapper.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/NetworkService.java
  services/src/northbound/src/main/java/org/openkilda/northbound/service/impl/NetworkServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/PathMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/PathsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/PathsService.java
Labels: C/NB, C/NBWORKER, Ready to Merge, area/api, area/testing

#2163 Improvement/switch detail ui improvement and switch rule fix
  services/src/openkilda-gui/ui/src/app/common/services/common.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/switch.service.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/rule-details/rule-details.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/rule-details/rule-details.component.ts
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-meters/switch-meters.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-meters/switch-meters.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: Ready to Merge, area/gui

#2180 Small fixes for functional tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/extension/SkippedTestsLogger.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormHeavyLoadSpec.groovy
Labels: Next Release, area/testing

#2182 Fix incorrect calculation of "burst_size".
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Meter.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/model/MeterTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
Labels: C/FL, C/SWMANAGER, Ready to Merge

#2187 Fix unstable functional test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
Labels: Next Release, area/testing

#2177 Fix the out of memory issue caused by classgraph lib
  services/src/kilda-core/kilda-persistence-neo4j/pom.xml
Labels: C/EVENT, C/FLOW, C/ISLSTATS, C/NBWORKER, C/PORTSTATE, C/STATS, C/SWMANAGER, Ready to Merge

#2160 Add test to verify ISL failure if port brought down while switch was off
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
Labels: On Review, area/testing

#2158 Add test that ensures proper isl failure when src+dst disconnect
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
Labels: On Review, area/testing

#2169 Add log wrapper for discovery topology
  services/wfm/src/main/java/org/openkilda/wfm/share/utils/AbstractLogWrapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/AbstractPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/LogicalBfdPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/PhysicalPort.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkSwitchService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/utils/KibanaLogWrapper.java
Labels: On Review
