Repository telstra/open-kilda, pull requests merged in 2019-12, with the labels that each got.

#2984 Ignore test that fails due to #2983
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ContentionV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2991 Fix flow segment verify issue on OF1.2 switches
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/ResetCountsFlagFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/utils/OfFlowPresenceVerifier.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
Labels: C/FL, Ready to Merge, bugfix

#2993 Fix false-negative meter's validation
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/meter/MeterVerifyCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/error/SwitchIncorrectMeterException.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/meter/MeterVerifyCommandTest.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/of/MeterSchemaBand.java
Labels: C/FL, Ready to Merge, bugfix

#2961 update See annotation for syncSwitch spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2985 Add cleanup verifier to check basic factors of a clean env
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/fixture/CleanupVerifierExtension.groovy
  services/src/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: Ready to Merge, area/testing, improvement

#2992 Refactor multi-reroute spec to work with bigger amount of flows
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2997 ignore fucn tests according to bugs
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#2999 Remove outdated/unused config option floodlight.request.timeout
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  services/wfm/src/main/resources/topology.properties.example
Labels: On Review, improvement

#3013 Feature/switch delete
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IAuthConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/SwitchController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/helper/RestClientManager.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/SwitchIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/log/constants/ActivityType.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/SwitchService.java
  services/src/openkilda-gui/src/main/resources/db/import-script_22.sql
  services/src/openkilda-gui/src/main/resources/db/import-script_23.sql
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/SwitchControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/util/TestSwitchMock.java
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.html
  services/src/openkilda-gui/ui/src/app/common/services/switch.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-add/flow-add.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-edit/flow-edit.component.html
  services/src/openkilda-gui/ui/src/app/modules/networkpath/networkpath.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/switches/switch-detail/switch-detail.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: C/GUI, On Review, Ready to Merge, area/gui, bug, feature

#2926 Fix performance degradation in FL Kafka Producer
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/AbstractWorker.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/DefaultWorker.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/IKafkaProducerService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/KafkaProducerService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/OrderAwareWorker.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchTrackingService.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/kafka/KafkaProducerServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchTrackingServiceTest.java
Labels: C/FL, Ready to Merge, improvement

#2958 add test for flows_reroute_using_default_encap_type feature toogle
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#2966 Fix northbound logging after update log4j to 2.11.0
  confd/templates/northbound/log4j2.xml.tmpl
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/Log4j2TimeMillisLookup.java
  services/src/northbound-service/northbound/src/main/resources/log4j2.xml.example
Labels: C/NBWORKER, Ready to Merge, area/northbound, bugfix

#2990 Refactor IslCostSpec to test 'unstable isl' behavior
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/UnstableIslSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing, improvement

#2994 Update all func tests to use v2 API wherever possible
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/network/PathsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/FlowStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/SimulateStatsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchActivationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3012 Change goToTable instruction for customer multi table flow
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge, bugfix

#3004 Revise flow priority reroute test with respect to h&s
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslMinPortSpeedSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3020 Add DB migration for reworked PCE
  services/neo4j/migrations/1.18-path-computation-strategy/1-path-computation-strategy.xml
  services/neo4j/migrations/1.18-path-computation-strategy/rollback.cql
Labels: DB Migration, On Review, area/pce, area/persistence

#2918 Switch LLDP 2: switch connected device models
  services/neo4j/init/neo4j-queries.cql
  services/neo4j/migrations/1.19-switch-connected-devices/1-add-switch-connected-devices-index-and-constraint.xml
  services/neo4j/migrations/1.19-switch-connected-devices/rollback.cql
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchConnectedDevice.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/SwitchConnectedDeviceRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchConnectedDevicesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchConnectedDevicesRepositoryTest.java
Labels: C/NEO4J, DB Migration, Ready to Merge, feature

#2914 Switch LLDP 3: catching on ISL ports
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/connected/ConnectedDevicesService.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/request/GetSwitchConnectedDevicesRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchConnectedDeviceDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchConnectedDevicesResponse.java
  services/src/messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchPortConnectedDevicesDto.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/switches/PortConnectedDevicesDto.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/switches/SwitchConnectedDeviceDto.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/switches/SwitchConnectedDevicesResponse.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/SwitchControllerV2.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/ConnectedDeviceMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/SwitchService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/SwitchServiceTest.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/ConnectedDeviceMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/connecteddevices/bolts/PacketBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/connecteddevices/service/PacketService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/connecteddevices/service/PacketServiceTest.java
Labels: C/CONNECTED, C/FL, Ready to Merge, feature

#2927 Add func tests for detecting lldp connected devices per-switch
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/VirtualEnvCleanupExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowConnectedDeviceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceV2Impl.java
Labels: Ready to Merge, area/testing, improvement

#2886 refactor tets with getSwithcFlow to cover #2885
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: Next Release, area/testing, improvement

#2952 Fix validation of encapsulation_type in v2 FlowUpdate API
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/FlowRequest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/mapper/RequestedFlowMapper.java
Labels: C/FLOW, C/FLOW-HS, C/NB, Next Release, bugfix

#2937 Handle invalid encapsulation_type in v2 FlowCreate API
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/converter/FlowMapperTest.java
Labels: C/FLOW, C/FLOW-HS, C/NB, Next Release, bugfix

#3014 Fix NullPointerException
  services/wfm/src/main/java/org/openkilda/wfm/topology/ping/bolt/TickDeduplicator.java
Labels: C/PING, Next Release, bugfix

#3017 Ignore port history tests due to #3007
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
Labels: Next Release, area/testing

#3023 Extend log message for missing rules
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/error/SwitchMissingFlowsException.java
Labels: C/FL, Next Release, improvement

#2986 Add test for devices interaction with default flow
  docker-compose.yml
  services/neo4j/Dockerfile
  services/neo4j/init/init.sh
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3037 Updated Dockerfile for building neo4j from off.site binaries
  docker-compose.yml
  services/neo4j/Dockerfile
  services/neo4j/init/init.sh
Labels: Ready to Merge, area/cicd, area/testing

#3060 ignore tests according to #3059
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableSwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3061 delete FlowPriorityRerouteSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3025 Fix removing customer port rule when flow H&S delete.
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/IngressFlowSegmentBase.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/IngressFlowSegmentInstallRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/IngressFlowSegmentRemoveRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/IngressFlowSegmentRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/IngressFlowSegmentVerifyRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/OneSwitchFlowInstallRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/OneSwitchFlowRemoveRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/OneSwitchFlowRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/OneSwitchFlowVerifyRequest.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/factory/IngressFlowSegmentRequestFactory.java
  services/src/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/api/request/factory/OneSwitchFlowRequestFactory.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentBase.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentInstallCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentRemoveCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentVerifyCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowInstallCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowRemoveCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowVerifyCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/ingress/of/IngressFlowModFactory.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/IngressCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentCommandJsonTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentInstallCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/IngressFlowSegmentRemoveCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowCommandJsonTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowInstallCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/OneSwitchFlowRemoveCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/of/IngressFlowModFactoryTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/of/IngressFlowSegmentInstallFlowModFactoryTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/ingress/of/OneSwitchFlowInstallFlowModFactoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/share/model/SpeakerRequestBuildContext.java
  services/wfm/src/main/java/org/openkilda/wfm/share/service/SpeakerFlowSegmentRequestBuilder.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/FlowProcessingAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/delete/actions/RemoveRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowCommandBuilder.java
Labels: C/FL, C/FLOW-HS, Ready to Merge, bugfix, tested

#3002 Fix error message when switch not exist
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchRuleServiceImpl.java
Labels: C/ROUTER, Ready to Merge, bugfix

#3018 Add comment that single-switch flow pings are actually useless
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
Labels: Ready to Merge, area/testing

#3042 Minor fixes in functional tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing

#3057 Add more stats verifications to existing tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/StatsHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceV2Spec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing

#3068 Fixed missing @Ignore import
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: On Review, area/testing, bugfix

#3063 improve flowHistorySpec, covers: 3031,3038
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3067 Fix fails of PacketServiceTest
  services/wfm/src/test/java/org/openkilda/wfm/topology/connecteddevices/service/PacketServiceTest.java
Labels: Ready to Merge, area/testing, bugfix

#3026 minor improvements in tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3058 add test "Flow ping can detect a broken path for a vxlan flow on an intermediate switch"
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3054 add tests for 3049 issue
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3062 Fix rollback in flow reroute
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnReceivedRemoveOrRevertResponseAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/RevertNewRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/utils/SpeakerRequestEmitter.java
Labels: C/FLOW-HS, Next Release, bugfix, priority/1-highest

#2785 Reroute topology updates flow status for flows
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/PathSegmentRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jPathSegmentRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/RerouteBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/reroute/service/RerouteServiceTest.java
Labels: C/REROUTE, Next Release, bugfix, priority/1-highest

#3086 Decrease parallelism for reply kafka spouts in flr
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
Labels: C/ROUTER, Next Release, bugfix
