Repository telstra/open-kilda, pull requests merged in 2019-06, with the labels that each got.

#2401 Add logging for ISL disco response in fl kafka producer and fl router
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/kafka/KafkaProducerService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterService.java
Labels: C/FL, C/ROUTER, Ready to Merge, enhancement

#2316 Refactor of PathVerificationService
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/DiscoveryPacket.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/DiscoveryPacketData.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/ping/PingService.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketOutTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketSignTest.java
Labels: C/FL, Ready to Merge, improvement, refactor

#2289 SwitchManager topology refactoring
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/SwitchValidateRequest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchManagerCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchManagerTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/SwitchSyncRulesCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/RouterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchSyncRulesManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/SwitchValidateManager.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncRulesFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/model/ValidationResult.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/SwitchSyncService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/SyncRulesServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchValidateServiceImplTest.java
Labels: C/NB, C/SWMANAGER, Ready to Merge, improvement

#2396 add verification that system deletes props for both directions, even …
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2424 fix test: System doesn't reroute main flow path when protected path is broken and new alt path is available
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2439 Fix failsafe transaction interface
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
Labels: On Review, bug

#2354 Detect and handle self looped ISL
  docs/design/network-discovery/uni-isl-FSM.png
  docs/design/network-discovery/uni-isl-FSM.puml
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/UniIslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/model/IslReference.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkUniIslServiceTest.java
Labels: C/NETWORK, Ready to Merge, improvement

#2412 Do not fail lab-service if openvswitch service is not running
  docker-compose.yml
  services/lab-service/lab/api/api.py
Labels: Ready to Merge, area/cicd, area/testing, bug

#2283 Do not reset defaultMaxBanwidth ISL's field on network topology start
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/model/IslDataHolder.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIslServiceTest.java
Labels: C/NETWORK, Ready to Merge, bug

#2423 Router remove stateful
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/BroadcastRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/DiscoveryBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/RequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/SpeakerRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/service/RouterUtils.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/floodlightrouter/bolts/DiscoveryBoltTest.java
Labels: C/ROUTER, Ready to Merge, bug

#2436 Make transaction bolt "non-stateful" in terms of storm
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/TransactionBolt.java
Labels: C/FLOW, On Review, bug

#2442 add verification that one transit vlan is created for a flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2445 Revert rules validate to use old code
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: C/NB, bug

#2432 Tests pinned + protected flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: area/testing, improvement

#2451 add tests for a pinned flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: On Review, area/testing, improvement

#2437 Add global flag to switch H&S reroutes
  confd/templates/atdd-staging/kilda.properties.tmpl
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2384 extend GRPC tests to iterate over all available firmware versions (6.4+)
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/AssumeProfileExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcCommonSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LicenseSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogicalPortSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2397 Use same transit VLAN for paths in both directions
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/TransitVlanRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPairRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jTransitVlanRepository.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/EncapsulationResourcesProvider.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManager.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/transitvlan/TransitVlanPool.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/BaseFlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/SwapPathsAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/TransitVlanCommandFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/Neo4jBasedTest.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/transitvlan/TransitVlanPoolTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/TransitVlanCommandFactoryTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImplTest.java
Labels: C/FLOW, Ready to Merge, improvement, tested

#2427 Add flow allocate protected path field migration
  services/neo4j/migrations/1.3-add-allocate-protected-path-field/1-add-allocate-protected-path-field-changelog.xml
Labels: C/NEO4J, Ready to Merge, improvement

#2328 Pinned flow
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Flow.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/PathSegment.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/UnidirectionalFlow.java
  services/src/kilda-core/kilda-model/src/test/java/org/openkilda/model/PathSegmentTest.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowPathRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/reroute/RerouteAffectedFlows.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/reroute/RerouteFlows.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/reroute/RerouteInactiveFlows.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlowDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowCreatePayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayloadToFlowConverter.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowUpdatePayload.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/IslService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/service/Sender.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/MessageSender.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/RerouteBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/reroute/service/RerouteServiceTest.java
Labels: C/FLOW, C/REROUTE, Ready to Merge, area/api, feature, tested

#2327 RTL: Part 2. Added round trip latency default rule
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/NoviFlowCopyFieldFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/DiscoveryPacketData.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/FeatureDetectorService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationCommonTests.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Cookie.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SpeakerSwitchView.java
Labels: C/FL, Ready to Merge, feature

#2467 Add round trip latency rule to install/delete rules API
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/DeleteRulesAction.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/InstallRulesAction.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
Labels: C/FL, On Review, bug

#2406 Added new Encapslation model class and Extended Encapsulation Enum
  services/neo4j/init/neo4j-queries.cql
  services/neo4j/migrations/1.5-switch-features/1-create-switch-features-changelog.xml
  services/neo4j/migrations/1.5-switch-features/rollback.cql
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchFeatures.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Vxlan.java
Labels: C/FLOW, C/NEO4J, Ready to Merge, area/vxlan_encapsulation

#2402 Add a VxLAN resource pool.
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/VxlanRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jVxlanRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jVxlanRepositoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/FlowResourcesConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManager.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/vxlan/VxlanEncapsulation.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/vxlan/VxlanPool.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/vxlan/VxlanPoolTest.java
Labels: C/NEO4J, Ready to Merge, area/vxlan_encapsulation

#2466 Add a feature toggle to reroute a flow with default encapsulation type.
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/FeatureToggles.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFeatureTogglesRepository.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/system/FeatureTogglesDto.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, C/NEO4J, Ready to Merge, area/vxlan_encapsulation, feature

#2444 add possibility to set specific controllet on an OVS
  confd/templates/atdd-staging/kilda.properties.tmpl
  confd/vars/main.yaml
  services/lab-service/lab/service/lockkeeper.py
  services/lab-service/lab/service/topology.py
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/config/TopologyConfig.java
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/TopologyConfig.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
Labels: Ready to Merge, area/testing, improvement

#2440 add test: check that protected flow allows traffic on main/protected paths
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2470 Add round trip rule into test
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
Labels: Ready to Merge, area/testing, improvement

#2475 Exclude switch object from switch features equals and hashCode
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchFeatures.java
Labels: Ready to Merge, bug

#2304 Swap endpoints for flow
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/SwapFlowEndpointRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/ctrl/state/visitor/DumpStateManager.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/flow/SwapFlowResponse.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SwapFlowDto.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/flows/SwapFlowEndpointPayload.java
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v2/flows/SwapFlowPayload.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/FlowControllerV2.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/FlowService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/TestConfig.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v1/TestMessageMock.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v2/FlowControllerTest.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/FlowServiceTest.java
  services/storm/conf/storm.yaml
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/ComponentType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/FlowTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/StreamType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/ErrorBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/FlowOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/NorthboundReplyBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/SplitterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/TransactionBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/FlowServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/FLOW, C/NB, Ready to Merge, area/api, feature

#2212 Improvements of Network topology dashboard logger.
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortReportFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkPortServiceTest.java
Labels: C/NETWORK, Ready to Merge, improvement

#2417 Allow both default and VLAN tagged flows for the same port
  docs/design/usecase/default-and-vlan-flow-endpoint.md
  services/src/floodlight-service/floodlight-modules/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/PushSchemeOutputCommands.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/FL, C/FLOW, Ready to Merge, feature

#2428 Fix switch status update logging
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopologyDashboardLogger.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
Labels: C/NETWORK, Ready to Merge, bug

#2454 Improve sync rules test to use path with max amount of switches
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/test-library/pom.xml
Labels: Ready to Merge, area/testing, improvement

#2469 Propagate API_HOST from lab-api into lab-service
  services/lab-service/lab/api/api.py
  services/lab-service/lab/service/service.py
Labels: Ready to Merge, area/testing, bug

#2471 RTL Part 3: Handle RTL packet in Floodlight
  services/src/configuration/src/main/java/org/openkilda/config/KafkaTopicsConfig.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannel.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/ping/PingResponseCommand.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/GroupPacketOutFeature.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/model/OfInput.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/DiscoveryPacket.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/DiscoveryPacketData.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/FeatureDetectorService.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/FloodlightTestCase.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/ping/PingResponseCommandTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/model/OfInputTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationCommonTests.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketOutTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslBaseLatency.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslOneWayLatency.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslRoundTripLatency.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/ComponentType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/Stream.java
Labels: C/FL, C/ROUTER, Next Release, feature

#2477 Add test that slowly discovers switches one by one
  confd/templates/atdd-staging/kilda.properties.tmpl
  confd/vars/main.yaml
  services/neo4j/migrations/README.md
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/config/TopologyConfig.java
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/TopologyConfig.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/TopologyConfig.java
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/fixture/rule/AbstractRuleExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/performance-tests/kilda.properties.example
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/BaseSpecification.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/DiscoverySpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Ready to Merge, area/testing, improvement

#2480 Fix to protected path tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Next Release, area/testing, bug

#2483 Fix assumeProfile failing if first feature is profile-dependent
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/AssumeProfileExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/spring/SpringContextExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
Labels: Ready to Merge, area/testing, bug

#2484 Fix: Remove the notification stream going to the HS kafka bolt.
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
Labels: C/ROUTER, Ready to Merge, bug

#2487 Fix functional test for pinned flow
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2488 Fix functional test for ISL min port speed feature
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslMinPortSpeedSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2489 Small refactoring of self-loop ISL test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2434 check that system allows to pass traffic via default and vlan flows when they are on the same port
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2350 Add an ability to choose encapsulation type in the CRUD flow over REST API.
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/UnidirectionalFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/FlowDto.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowCreatePayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowEncapsulationType.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowPayload.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowUpdatePayload.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v1/TestMessageMock.java
  services/wfm/src/main/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManager.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/TestFlowBuilder.java
  services/wfm/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  services/wfm/src/test/java/org/openkilda/wfm/share/mappers/FlowMapperTest.java
Labels: C/FLOW, C/NB, Ready to Merge, area/vxlan_encapsulation, feature

#2492 Update GRPC tests to CRUD BFD logical ports
  services/src/functional-tests/src/main/resources/META-INF/services/org.codehaus.groovy.runtime.ExtensionModule
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcCommonSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LicenseSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogicalPortSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/grpc/GrpcService.java
Labels: area/testing, improvement

#2499 Restored cookie mismatch debug log level
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/model/OfInput.java
Labels: C/FL, Next Release, bug

#2502 ignore test, functionality is not implemented yet
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2507 Fix for separate functional test execution
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/spring/SpringContextExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
Labels: Ready to Merge, area/testing

#2392 Add functional tests for flow swap endpoint feature
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, feature

#2512 Partially revert PR2212 - deduplicate port event notifications
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
Labels: C/NETWORK, Ready to Merge

#2508 PCE takes into account encapsulation type
  services/neo4j/migrations/1.6-encapsulation-type/1-upper-case-flow-encapsulation-type-changelog.xml
  services/neo4j/migrations/1.6-encapsulation-type/rollback.cql
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/Switch.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/SwitchFeatures.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/IslRepository.java
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/SwitchFeaturesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/converters/FlowEncapsulationTypeConverter.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchFeaturesRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/converters/FlowEncapsulationTypeConverterTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepositoryTest.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jSwitchFeaturesRepositoryTest.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/AvailableNetworkFactory.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/PathComputer.java
  services/src/kilda-pce/src/main/java/org/openkilda/pce/impl/InMemoryPathComputer.java
  services/src/kilda-pce/src/test/java/org/openkilda/pce/impl/InMemoryPathComputerTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/mapper/RequestedFlowMapper.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/model/RequestedFlow.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/PathsService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowCreateServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkSwitchServiceTest.java
Labels: C/FLOW, DB Migration, Ready to Merge, area/pce, area/vxlan_encapsulation, feature

#2446 add tests to smoke iteration
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslMinPortSpeedSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/logging/CheckLoggingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/network/PathsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/OpenTsdbSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2486 Design for representing protected path status in API
  docs/design/solutions/protected-paths/protected-path-status-api.md
Labels: Ready to Merge, area/api

#2500 extend default flow tests
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2504 Fix TagExtension to properly count execution times for a tag
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
Labels: Ready to Merge, area/testing, bug

#2514 fix logging for the setLinkBfd method
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, improvement

#2496 Make 'ovs-meters-enabled' configurable
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/vars/main.yaml
Labels: Ready to Merge, area/config

#2463 Make FSM independent (network-topology)
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/AntiFlapFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/BfdGlobalToggleFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/DecisionMakerFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/UniIslFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/bfd/BfdPortFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/port/PortReportFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkAntiFlapService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkBfdGlobalToggleService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkBfdPortService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkDecisionMakerService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkIslService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkPortService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkSwitchService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/NetworkUniIslService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkPortServiceTest.java
Labels: C/NETWORK, Ready to Merge, bug

#2346 Ensure ISL use link props data
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIslServiceTest.java
Labels: C/NETWORK, Ready to Merge, improvement

#2404 add possibility to use the `verifyRulesOnProtectedFlow` method when we have 1+ flows
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/FlowSteps.java
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing, improvement

#2473 Return diverse group flows id in get flow response
  docs/design/solutions/pce-diverse-flows/flow-get-with-diverse-group.md
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/flow/FlowReadResponse.java
  services/src/messaging/src/main/java/org/openkilda/messaging/payload/flow/FlowResponsePayload.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/FlowController.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/FlowService.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  services/src/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v1/TestMessageMock.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, C/NB, Ready to Merge, area/api, feature, tested

#2510 Fix NPE in SwManager RouterBolt
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/bolt/RouterBolt.java
Labels: C/SWMANAGER, Ready to Merge, bug

#2520 Fix log message for validate switch request.
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: C/NB, Ready to Merge, bug

#2485 Issue 647 add vxlan methods to fl rebased
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerOF12Test.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/PushSchemeOutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/ReplaceSchemeOutputCommands.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallEgressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallIngressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallTransitFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/DeleteRulesCriteria.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/Constants.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallEgressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallIngressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallTransitFlowTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowCommandFactory.java
Labels: C/FL, C/FLOW, C/NB, Next Release, area/vxlan_encapsulation, feature

#2540 fix test "Able to swap main and protected paths manually"
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2521 Tunnel id match extended
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerOF12Test.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/PushSchemeOutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/ReplaceSchemeOutputCommands.java
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_egress_none_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_egress_pop_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_egress_push_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_egress_replace_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_ingress_none_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_ingress_pop_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_ingress_push_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_ingress_replace_flow.json
  services/src/floodlight-service/floodlight-modules/src/test/resources/install_transit_flow.json
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallEgressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallIngressFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/flow/InstallTransitFlow.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/DeleteRulesCriteria.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/Constants.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/AbstractSerializerTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallEgressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallIngressFlowTest.java
  services/src/messaging/src/test/java/org/openkilda/messaging/command/flow/InstallTransitFlowTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowCommandFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/TransitVlanCommandFactory.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/switchmanager/service/impl/CommandBuilderImpl.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/service/FlowCommandFactoryTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/SwitchSyncServiceImplTest.java
Labels: C/FL, C/FLOW, Ready to Merge, area/vxlan_encapsulation, feature

#2519 add smoke_switches tag, and mark needed tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/Tag.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2530 RTL Part 5: change handling of OpenTsdb records
  services/src/messaging/src/main/java/org/openkilda/messaging/info/event/IslStatusUpdateNotification.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/bolts/CacheBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/bolts/IslStatsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/bolts/IslStatusUpdateBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/carriers/IslStatsCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/model/StreamType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/service/IslLatencyService.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/service/IslStatsService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/TestKafkaConsumer.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/service/IslLatencyServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/service/IslStatsServiceTest.java
Labels: C/ISLLATENCY, Ready to Merge, feature

#2527 Changed 'isl.latency' to 'isl.rtt' metric in GUI
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.html
Labels: C/GUI, Ready to Merge, area/gui, feature

#2541 Fix correlation id checks for swagger ui
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/SwaggerConfig.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationFilter.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationInspectorFilter.java
Labels: C/NB, On Review, bug

#2548 Data migration for supported_transit_encapsulation
  services/neo4j/migrations/1.7-supported-transit-encapsulation/1-supported-transit-encapsulation-to-switch-features-changelog.xml
  services/neo4j/migrations/1.7-supported-transit-encapsulation/rollback.cql
Labels: C/NEO4J, On Review, bug
