Repository telstra/open-kilda, pull requests merged in 2019-05, with the labels that each got.

#2318 Fix resource allocation below the low boundaries
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/FlowPair.java
  services/src/kilda-core/kilda-model/src/main/java/org/openkilda/model/UnidirectionalFlow.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowCookieRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowMeterRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jTransitVlanRepository.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
Labels: C/FLOW, Ready to Merge

#2250 Add error response for CRUD Flow when features disabled
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
  services/src/messaging/src/main/java/org/openkilda/messaging/error/ErrorType.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundExceptionHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
Labels: C/FLOW, Ready to Merge, area/northbound

#2260 Add fields to SwitchDto from database model.
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/switches/SwitchDto.java
  services/src/northbound-service/nb-api/src/test/java/org/openkilda/northbound/dto/JsonSerializationTest.java
  services/src/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/SwitchMapper.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/wfm/src/main/java/org/openkilda/wfm/share/mappers/SwitchMapper.java
  services/wfm/src/test/java/org/openkilda/wfm/share/mappers/SwitchMapperTest.java
Labels: C/NB, C/NBWORKER, Ready to Merge

#2286 Log discovery data received by speaker
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/IslFsm.java
Labels: C/NETWORK, Next Release

#2303 Slightly improve lab service api parallelism
  services/lab-service/lab/api/api.py
  services/lab-service/lab/service/service.py
Labels: Ready to Merge, area/testing

#2306 Expose ElasticSearch ports.
  docker-compose.yml
Labels: Next Release

#2308 Add test to verify excess rules and meters deletion while sync
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/switches/SwitchSyncRequest.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing

#2309 Adding feature to import and export topology screen settings
  services/src/openkilda-gui/ui/src/app/app.module.ts
  services/src/openkilda-gui/ui/src/app/modules/settings/session/session.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/affected-isl/affected-isl.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/export-topology-setting/export-topology-setting.component.css
  services/src/openkilda-gui/ui/src/app/modules/topology/export-topology-setting/export-topology-setting.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/export-topology-setting/export-topology-setting.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/export-topology-setting/export-topology-setting.component.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/import-topology-setting/import-topology-setting.component.css
  services/src/openkilda-gui/ui/src/app/modules/topology/import-topology-setting/import-topology-setting.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/import-topology-setting/import-topology-setting.component.spec.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/import-topology-setting/import-topology-setting.component.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/topology-menu/topology-menu.component.css
  services/src/openkilda-gui/ui/src/app/modules/topology/topology-menu/topology-menu.component.html
  services/src/openkilda-gui/ui/src/app/modules/topology/topology-menu/topology-menu.component.ts
  services/src/openkilda-gui/ui/src/app/modules/topology/topology.component.ts
  services/src/openkilda-gui/ui/src/assets/images/18x18/inbox-in-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/inbox-in-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/inbox-out-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/inbox-out-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/link-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/link-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/unlink-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/18x18/unlink-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/inbox-in-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/inbox-in-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/inbox-out-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/inbox-out-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/link-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/link-regular-white.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/unlink-regular-black.png
  services/src/openkilda-gui/ui/src/assets/images/36x36/unlink-regular-white.png
  services/src/openkilda-gui/ui/src/styles.css
Labels: Ready to Merge, area/gui

#2297 Refactoring of functional tests to use topology helper where possible
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/SwitchPair.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/network/PathsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing

#2192 #1060 Add check for conflicts with ISL ports in FlowValidator.
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/IslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jIslRepositoryTest.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flow/validation/FlowValidator.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/FlowTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
Labels: C/FLOW, Ready to Merge

#2241 Refactoring of VerificationPacket class
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/IPathVerificationService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/VerificationPacket.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/web/PathDiscover.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/web/PathVerificationServiceWebRoutable.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketInTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketOutTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketSignTest.java
Labels: C/FL, Improvement, Ready to Merge, refactor

#2317 Misc improvements in tests
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/ChaosSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/SimulateStatsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2320 Adding feature to display meter stats graph
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/IConstants.java
  services/src/openkilda-gui/src/main/java/org/openkilda/constants/OpenTsDb.java
  services/src/openkilda-gui/src/main/java/org/openkilda/controller/StatsController.java
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/StatsIntegrationService.java
  services/src/openkilda-gui/src/main/java/org/openkilda/service/StatsService.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/StatsControllerTest.java
  services/src/openkilda-gui/src/test/java/org/openkilda/controller/mockdata/TestMockStats.java
  services/src/openkilda-gui/src/test/java/org/openkilda/test/BaseTest.java
  services/src/openkilda-gui/ui/src/app/common/dygraph/dygraph.component.ts
  services/src/openkilda-gui/ui/src/app/common/services/dygraph.service.ts
  services/src/openkilda-gui/ui/src/app/common/services/flows.service.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-graph/flow-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-graph/flow-graph.component.ts
Labels: Ready to Merge, area/gui, feature

#2323 Extend switch validation spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2324 Use virtual/hardware tags instead of assumptions directly in test
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/TestDataLoggingExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/AssumeProfileExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/spring/ContextAwareGlobalExtension.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/Tag.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/tags/TagExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcBaseSpecification.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormHeavyLoadSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/OpenTsdbSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: Improvement, Ready to Merge, area/testing

#2326 ADD test: System is able to set min port speed for isl capacity
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslMinPortSpeedSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2329 Use docker memlimits for 16GB setup as default (instead of unlimited)
  .env.example
  docker-compose.yml
Labels: Improvement, Ready to Merge, area/config

#2340 Add EnduranceSpec with 'simulation' test
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2341 REFACTOR: rename method according to internal convention
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Improvement, Ready to Merge, area/testing

#2352 Refactor flow crud test to avoid isl-port endpoints
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
Labels: Ready to Merge, area/testing

#2345 Fix KafkaBreaker hardcoded topic name
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/pom.xml
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/KafkaTopicNameConfig.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/FloodlightKafkaConnectionSpec.groovy
  services/src/test-library/pom.xml
  services/src/test-library/src/main/java/org/openkilda/testing/config/KafkaTopicNameConfig.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/kafka/KafkaBreaker.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/kafka/KafkaBreakerImpl.java
Labels: Ready to Merge, area/testing

#2344 Fix API PATCH /flows/{flow-id}.
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/FlowOperationsBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java
Labels: C/NBWORKER, Ready to Merge

#2330 extend existing 'Unable to create a flow on an isl port' test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2261 ADD test: Able to synchronize rules for a flow with protected path
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
Labels: On Review, area/testing

#2262 ADD test: Able to validate flow with protected path
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
Labels: On Review, area/testing

#2264 ADD test: Able to validate switch rules in case flow is created with protected path
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
Labels: On Review, area/testing

#2269 ADD: System is able to reroute(intentional) flow with protected according to the priority field
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
Labels: On Review, area/testing

#2365 Fix unstable meters test to properly wait for flow update to complete
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Ready to Merge, area/testing, bug

#2325 Use OF groups for discovery process
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/feature/GroupPacketOutController.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/service/FeatureDetectorService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/service/FeatureDetectorServiceTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
  services/src/messaging/src/main/java/org/openkilda/messaging/model/SpeakerSwitchView.java
Labels: C/FL, On Review, feature

#2278 ADD tests: protected path
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPriorityRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: On Review, area/testing, feature

#2305 MultiFL statistics documentation.
  docs/design/fl-statistics/README.md
  docs/design/fl-statistics/fl-statistics-kafka-topics.puml
  docs/design/fl-statistics/fl-statistics-sequence.puml
  docs/design/fl-statistics/fl_statistics_kafka_topics.png
  docs/design/fl-statistics/fl_statistics_sequence.png
Labels: Ready to Merge, area/docs

#2279 MultiFL. Add FL for statistics.
  .env.example
  confd/conf.d/floodlight.floodlightkildaStats.toml
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/templates/floodlight/floodlightkildaStats.properties.tmpl
  confd/templates/wfm/topology.properties.tmpl
  confd/vars/main.yaml
  docker-compose.yml
  services/lab-service/lab/service/topology.py
  services/src/configuration/src/main/java/org/openkilda/config/KafkaTopicsConfig.java
  services/src/floodlight-modules/Dockerfile
  services/src/floodlight-modules/entrypoint.sh
  services/src/floodlight-modules/src/main/java/net/floodlightcontroller/core/internal/DefaultSwitchRoleService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/KafkaChannel.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/command/inventory/ListSwitchCommand.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/command/statistics/StatsCommand.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/KafkaMessageCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/StatsKafkaMessageCollector.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/dispatcher/ListSwitchDispatcher.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/dispatcher/StatsRequestDispatcher.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/IStatisticsService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManagerConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchTrackingService.java
  services/src/floodlight-modules/src/main/resources/META-INF/services/net.floodlightcontroller.core.module.IFloodlightModule
  services/src/floodlight-modules/src/main/resources/floodlightkilda.properties.example
  services/src/floodlight-modules/src/main/resources/floodlightkildaStats.properties.example
  services/src/floodlight-modules/src/test/java/net/floodlightcontroller/core/internal/DefaultSwitchRoleServiceTest.java
  services/src/functional-tests/kilda.properties.example
  services/src/messaging/src/main/java/org/openkilda/messaging/command/stats/StatsRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/switches/ListSwitchRequest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/info/switches/ListSwitchResponse.java
  services/wfm/app/Makefile
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/ComponentType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/Stream.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/floodlightrouter/bolts/BroadcastRequestBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/StatsTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/StatsTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/stats/bolts/StatsRequesterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/StatsRouterComponentType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/StatsRouterStreamType.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/StatsRouterTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/StatsRouterTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/bolts/StatsRouterBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/service/MessageSender.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/statsrouter/service/StatsRouterService.java
  services/wfm/src/main/resources/topology.properties.example
  services/wfm/src/test/java/org/openkilda/wfm/topology/floodlightrouter/bolts/DiscoveryBoltTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/statsrouter/service/StatsRouterServiceTest.java
Labels: Ready to Merge, area/floodlight, area/messages, area/stats, area/storm, area/topo, feature

#2374 Minor fixes in meters centec test to keep up with latest code updates
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/spring/SpringContextExtension.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2380 Fix perf test to respect existing topology and properly avoid isl ports
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceSpec.groovy
  services/src/performance-tests/src/test/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
Labels: Ready to Merge, area/testing, bug

#2312 Rename IslStatsTopology to IslLatencyTopology and refactor
  docs/design/kafka.md
  services/wfm/app/Makefile
  services/wfm/src/checkstyle/checkstyle-suppress-known-issues.xml
  services/wfm/src/main/java/org/openkilda/wfm/topology/event/OfeLinkBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopologyConfig.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/bolts/IslStatsBolt.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/IslLatencyTopologyTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/isllatency/bolts/IslStatsBoltTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/stats/IslStatsTopologyTest.java
Labels: C/ISLSTATS, Improvement

#2379 fix tests for protected path according to staging env
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Improvement, Ready to Merge, area/testing

#2385 Remove unhandledInput from IslStatsBolt
  services/wfm/src/main/java/org/openkilda/wfm/topology/isllatency/bolts/IslStatsBolt.java
Labels: C/ISLSTATS, On Review, bug

#2389 Hotfix for update max bandwith
  services/src/api/src/main/java/org/openkilda/northbound/dto/links/LinkMaxBandwidthDto.java
  services/src/api/src/main/java/org/openkilda/northbound/dto/links/LinkMaxBandwidthRequest.java
Labels: Ready to Merge, improvement, techdebt

#1860 Design for create flow using H&S approach
  docs/design/hub-and-spoke/crud/create/flow-create-fsm.dot
  docs/design/hub-and-spoke/crud/create/flow-create-fsm.png
Labels: C/FLOW, On Review, area/docs, area/storm, epic/hub@spoke

#2399 Added role and region as custom fields to FL logback config
  confd/templates/floodlight/logback.xml.tmpl
Labels: C/FL, Ready to Merge, area/config, improvement

#2347 Add functional tests for BFD feature
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/steps/TopologyVerificationSteps.java
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslCostSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/model/CustomTopology.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/tools/IslUtils.java
Labels: Ready to Merge, area/testing, improvement

#2405 Persist python lib versions for traffexam
  services/lab-service/traffexam/requirements.txt
Labels: Ready to Merge, improvement

#2403 Adding feature to toggle the menu sidebar
  services/src/openkilda-gui/ui/src/app/app.component.ts
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.css
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.html
  services/src/openkilda-gui/ui/src/app/common/components/sidebar/sidebar.component.ts
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.html
  services/src/openkilda-gui/ui/src/app/modules/isl/isl-detail/isl-detail.component.ts
  services/src/openkilda-gui/ui/src/styles.css
Labels: C/GUI, Ready to Merge, area/gui

#2321 ADD test: "System is able to collect stats from the statistic and management controllers"
  confd/templates/atdd-staging/kilda.properties.tmpl
  confd/vars/main.yaml
  services/lab-service/lab/service/lockkeeper.py
  services/lab-service/lab/service/topology.py
  services/src/atdd-staging/src/main/java/org/openkilda/atdd/staging/config/TopologyConfig.java
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/config/TopologyConfig.java
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/lockkeeper/LockKeeperVirtualImpl.java
Labels: Ready to Merge, area/testing, improvement

#2364 Add test for issue #2363
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/WfmManipulator.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/StormLcmSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2367 add test: check that protected flow allows traffic on main/protected paths
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2409 rename correlation id for functional and grpc tests
  services/src/test-library/src/main/java/org/openkilda/testing/service/grpc/GrpcServiceImpl.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, improvement

#2393 Create changelog generator script
  tools/changelog-generator/changelog-generator.py
  tools/changelog-generator/requirements.txt
  tools/changelog-generator/template.jinja2
Labels: Ready to Merge, area/ops, improvement

#2368 System doesn't reroute main flow path when protected path is broken and new alt path is available
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#2276 #2053 Make broadcast MAC address for a discovery packet configurable.
  confd/templates/floodlight/floodlightkilda.properties.tmpl
  confd/templates/floodlight/floodlightkildaStats.properties.tmpl
  confd/vars/main.yaml
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/IPathVerificationService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationServiceConfig.java
  services/src/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-modules/src/main/resources/floodlightkilda.properties.example
  services/src/floodlight-modules/src/main/resources/floodlightkildaStats.properties.example
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/kafka/ReplaceInstallFlowTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/pathverification/PathVerificationPacketOutTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerOF12Test.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
  services/src/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge

#2421 ignore broken test due to incorrect logic in test
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
Labels: Next Release, area/testing

#2425 Log the root cause of OGM mapping exception in repositories
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jGenericRepository.java
Labels: C/FLOW, C/NBWORKER, C/PING, On Review
