Repository telstra/open-kilda, pull requests merged in 2020-02, with the labels that each got.

#3133 Reroute affected flows on switch up event
  docs/design/network-discovery/switch-FSM.png
  docs/design/network-discovery/switch-FSM.puml
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowPathRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPathRepositoryTest.java
  services/src/messaging/src/main/java/org/openkilda/messaging/command/reroute/RerouteAffectedInactiveFlows.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/utils/RerouteRetryQueue.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/NetworkTopology.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/controller/sw/SwitchFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/service/ISwitchCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/sw/SwitchHandler.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/bolts/RerouteBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/reroute/service/RerouteService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/utils/RerouteRetryQueueTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkIntegrationCarrier.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/network/service/NetworkSwitchServiceTest.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/reroute/service/RerouteServiceTest.java
Labels: C/NETWORK, C/REROUTE, Next Release, bugfix

#3158 Skip corrupted flow while doing periodic pings invalidation.
  services/wfm/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcherTest.java
Labels: C/PING, Next Release, bugfix

#3159 Fixed incorrect log message in case of v2 FlowDelete
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/delete/actions/OnFinishedAction.java
Labels: C/FLOW-HS, Next Release, bugfix

#3111 minor improvement in flowHistoryV2
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3114 remove ignore annotation according to 2904
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3115 add test for #1150
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3116 minor improvements in featureToogle spec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3126 add test: "System reroutes flow to more preferable path while updating"
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3040 Add test for partial update API
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PartialUpdateSpec.groovy
  services/src/northbound-service/nb-api/src/main/java/org/openkilda/northbound/dto/v1/flows/FlowPatchDto.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundService.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/northbound/NorthboundServiceImpl.java
Labels: Ready to Merge, area/testing, feature

#3079 Add test for flow with endpoint vlan matching transit vlan
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/kilda-core/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/TransitVlanRepository.java
  services/src/kilda-core/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jTransitVlanRepository.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  services/src/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: Ready to Merge, area/testing, improvement

#3096 Supply most tests with comprehensive cleanup and mark them as @Tidy
  services/src/functional-tests/README.md
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/BandwidthV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/DefaultFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversityV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowSyncV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/GrpcCommonSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/grpc/LogicalPortSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/FlowRulesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortAntiflapSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortHistorySpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchDeleteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchMaintenanceSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPortConfigSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3101 Fix flow creation in MultiRerouteSpec
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
Labels: Ready to Merge, area/testing, improvement

#3102 Minor fixes to make stats verifications work properly on stage env
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/StatsHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3113 Add test for #3087
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3120 Tests stability improved
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/StatsHelper.groovy
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/thread/FlowHistoryConstants.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowHistoryV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PinnedFlowV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/PortPropertiesSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  services/src/performance-tests/src/main/groovy/org/openkilda/performancetests/helpers/TopologyHelper.groovy
Labels: Ready to Merge, area/testing, improvement

#3122 Update EnduranceSpec with more assertions
  services/src/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/StatsHelper.groovy
  services/src/performance-tests/src/test/groovy/org/openkilda/performancetests/spec/EnduranceV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3132 Add test for #3128
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/RollbacksSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesV2Spec.groovy
Labels: Next Release, area/testing

#3162 Add reroute retries when transit rules can't be installed or verified
  confd/vars/main.yaml
  services/src/functional-tests/kilda.properties.example
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/AutoRerouteV2Spec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/RollbacksSpec.groovy
  services/src/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesV2Spec.groovy
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/FlowRerouteHubBolt.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnReceivedInstallResponseAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateNonIngressRulesAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/model/FlowRerouteFact.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteHubCarrier.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteService.java
  services/wfm/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowRerouteServiceTest.java
Labels: C/FLOW-HS, Next Release, bugfix

#3167 Fix reroute request filling in Flow H&S topology.
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/FlowRerouteFsm.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnReceivedInstallResponseAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
  services/wfm/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateNonIngressRulesAction.java
Labels: C/FLOW-HS, Next Release, bugfix

#3156 Dump all switches to return visible switches
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/ISwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  services/src/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchTrackingService.java
  services/src/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchTrackingServiceTest.java
Labels: C/FL, Next Release, bugfix, priority/2-high

#3178 reorganize-project-change-docker-context: Change docker build context…
  .gitignore
  Makefile
  docker-compose.yml
  docker/.gitignore
  docker/atdd-staging/Dockerfile
  docker/base/kilda-base-lab-service/Dockerfile
  docker/elasticsearch/Dockerfile
  docker/floodlight-modules/Dockerfile
  docker/grpc-service/Dockerfile
  docker/lab-service/Dockerfile
  docker/northbound/Dockerfile
  docker/wfm/Dockerfile
  services/src/openkilda-gui/Dockerfile
  src-java/base-topology/base-storm-topology/build.gradle
  src-java/build.gradle
  src-java/floodlight-service/floodlight-modules/build.gradle
  src-java/testing/atdd-staging/build.gradle
  src-python/lab-service/Makefile
  src-python/lab-service/lab/Makefile
  src-python/lab-service/traffexam/Makefile
Labels: Ready to Merge, area/cicd, improvement

#3181 Restore RollbacksSpec
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/RollbacksSpec.groovy
Labels: Ready to Merge, area/testing, bugfix

#3189 Copy log config to lab-api container
  Makefile
  docker/.gitignore
  docker/lab-service/Dockerfile
  src-python/lab-service/lab/Makefile
Labels: On Review, area/testing

#3195 Fix elasticsearch image build
  Makefile
Labels: Ready to Merge, bugfix

#3190 Fix python3 dependency list
  README.md
Labels: Ready to Merge, area/docs

#3198 test improvements
  src-java/testing/functional-tests/build.gradle
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowPingSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/VxlanFlowV2Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/toggles/FeatureTogglesV2Spec.groovy
Labels: Ready to Merge, area/testing, improvement

#3211 Fix running Storm topology locally (in dev environment)
  src-java/build.gradle
  src-java/connecteddevices-topology/connecteddevices-storm-topology/build.gradle
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/build.gradle
  src-java/flow-topology/flow-storm-topology/build.gradle
  src-java/flowhs-topology/flowhs-storm-topology/build.gradle
  src-java/isllatency-topology/isllatency-storm-topology/build.gradle
  src-java/nbworker-topology/nbworker-storm-topology/build.gradle
  src-java/network-topology/network-storm-topology/build.gradle
  src-java/opentsdb-topology/opentsdb-storm-topology/build.gradle
  src-java/ping-topology/ping-storm-topology/build.gradle
  src-java/portstate-topology/portstate-storm-topology/build.gradle
  src-java/reroute-topology/reroute-storm-topology/build.gradle
  src-java/stats-topology/stats-storm-topology/build.gradle
  src-java/statsrouter-topology/statsrouter-storm-topology/build.gradle
  src-java/swmanager-topology/swmanager-storm-topology/build.gradle
Labels: Ready to Merge, area/cicd

#3193 Fix build.gradle - proper task reference in buildAndCopyArtifacts.
  src-java/build.gradle
Labels: Ready to Merge, area/cicd

#3192 Fix running func-tests and perf-tests in IDEA.
  src-java/testing/functional-tests/build.gradle
  src-java/testing/performance-tests/build.gradle
Labels: Ready to Merge, area/cicd

#3204 Downgrade Kafka and Spring dependencies to pre-restructuring versions
  src-java/build.gradle
  src-java/northbound-service/northbound/build.gradle
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/messaging/kafka/KafkaMessageListener.java
Labels: Ready to Merge, area/cicd, bugfix

#3191 Expose OF transaction id into speaker logs
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/ping/PingResponseCommand.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/connected/ConnectedDevicesService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/session/Session.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/statistics/StatisticsService.java
Labels: C/FL, Ready to Merge, improvement

#2876 Design for LLDP connected devices on switch
  docs/design/connected-devices-lldp-switch/connected-devices-lldp.md
  docs/design/connected-devices-lldp-switch/egress_table.png
  docs/design/connected-devices-lldp-switch/ingress_table.png
  docs/design/connected-devices-lldp-switch/input_table.png
  docs/design/connected-devices-lldp-switch/lldp-catching-customer.puml
  docs/design/connected-devices-lldp-switch/lldp-catching-isl.puml
  docs/design/connected-devices-lldp-switch/lldp-catching-other.puml
  docs/design/connected-devices-lldp-switch/lldp_catching_customer.png
  docs/design/connected-devices-lldp-switch/lldp_catching_isl.png
  docs/design/connected-devices-lldp-switch/lldp_catching_other.png
  docs/design/connected-devices-lldp-switch/post_ingress_table.png
  docs/design/connected-devices-lldp-switch/pre_ingress_table.png
  docs/design/connected-devices-lldp-switch/transit_table.png
Labels: Ready to Merge, area/docs, feature

#3055 Fixed issue in flow path stats graph
  services/src/openkilda-gui/src/main/java/org/openkilda/integration/service/StatsIntegrationService.java
  services/src/openkilda-gui/ui/src/app/common/dygraph/dygraph.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-detail/flow-detail.component.ts
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.html
  services/src/openkilda-gui/ui/src/app/modules/flows/flow-path-graph/flow-path-graph.component.ts
Labels: C/GUI, Ready to Merge, area/gui, bugfix

#3066 Fixed security vulnerability in kildagui
  services/src/openkilda-gui/pom.xml
Labels: C/GUI, Ready to Merge, area/gui

#3030 Imrovement for gzip compression in UI and browser
  confd/templates/gui/application.properties.tmpl
Labels: C/GUI, Ready to Merge, area/gui, improvement

#3069 Fixed flow ping for VXLAN flows
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge, bugfix

#3075 [Server 42] Design for Round Trip Ping rules
  docs/design/server42/ping-flow-with-round-trip-latency/README.md
  docs/design/server42/ping-flow-with-round-trip-latency/all_rules_diagram.png
  docs/design/server42/ping-flow-with-round-trip-latency/all_rules_table.pdf
  docs/design/server42/ping-flow-with-round-trip-latency/catch_rule.png
  docs/design/server42/ping-flow-with-round-trip-latency/input_rule.png
  docs/design/server42/ping-flow-with-round-trip-latency/pre_ingress_rule.png
  docs/design/server42/ping-flow-with-round-trip-latency/turning_rule.png
  docs/design/server42/ping-flow-with-round-trip-latency/vlan_encapsulation.png
  docs/design/server42/ping-flow-with-round-trip-latency/vxlan_encapsulation.png
  docs/design/server42/ping-flow-with-round-trip-latency/vxlan_transit_rule.png
Labels: Ready to Merge, area/docs, feature

#3088 Fix the responses in swagger docs.
  src-java/northbound-service/northbound-api/src/main/java/org/openkilda/northbound/dto/v1/switches/DeleteLinkResult.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/FeatureTogglesController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/FlowController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/LinkController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/NetworkController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
Labels: C/NB, Ready to Merge, bugfix

#3084 Fixed unit test for multi table
  src-java/kilda-persistence-neo4j/src/test/java/org/openkilda/persistence/repositories/impl/Neo4jFlowRepositoryTest.java
Labels: Ready to Merge, area/testing, improvement

#3112 improvement: generate topology with one-way link only
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
Labels: Ready to Merge, area/testing, improvement

#3153 Get rid of flow wrappers in Ping topology.
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/model/Ping.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/FlowServiceImpl.java
  src-java/ping-topology/ping-messaging/src/main/java/org/openkilda/messaging/model/BidirectionalFlowDto.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FailReporter.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/PingProducer.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/model/PingContext.java
  src-java/ping-topology/ping-storm-topology/src/test/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcherTest.java
Labels: C/PING, Ready to Merge, improvement

#3121 Design for ARP connected devices on switch
  docs/design/connected-devices-arp/README.md
  docs/design/connected-devices-arp/arp-catching-customer.puml
  docs/design/connected-devices-arp/arp-catching-isl.puml
  docs/design/connected-devices-arp/arp-catching-other.puml
  docs/design/connected-devices-arp/arp_catching_customer.png
  docs/design/connected-devices-arp/arp_catching_isl.png
  docs/design/connected-devices-arp/arp_catching_other.png
  docs/design/connected-devices-arp/ingress_drop.png
  docs/design/connected-devices-arp/input_drop.png
  docs/design/connected-devices-arp/input_flow.png
  docs/design/connected-devices-arp/isl_rule.png
  docs/design/connected-devices-arp/one_switch_flow.png
  docs/design/connected-devices-arp/vlan_flow.png
  docs/design/connected-devices-arp/vxlan_flow.png
Labels: Ready to Merge, area/docs, feature

#3208 improve building procedure for kilda-base-lab-service image
  docker/base/kilda-base-lab-service/Dockerfile
Labels: Ready to Merge, improvement

#3174 Correct handle empty affected isl set in reroute throttling
  src-java/reroute-topology/reroute-storm-topology/src/main/java/org/openkilda/wfm/topology/reroute/service/ReroutesThrottling.java
  src-java/reroute-topology/reroute-storm-topology/src/test/java/org/openkilda/wfm/topology/reroute/service/ReroutesThrottlingTest.java
Labels: C/REROUTE, Ready to Merge, bugfix

#3039 Fix MeterVerifyCommand to handle inaccurate meter bandwidth and burst
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/AbstractSpeakerCommandTest.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/meter/MeterVerifyCommandTest.java
  src-java/kilda-model/src/main/java/org/openkilda/model/of/MeterSchemaBand.java
Labels: C/FL, Ready to Merge, bugfix

#3161 Get rid of the FlowPair wrapper.
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/mappers/FlowMapperTest.java
  src-java/flow-topology/flow-storm-topology/src/main/java/org/openkilda/wfm/topology/flow/bolts/CrudBolt.java
  src-java/flow-topology/flow-storm-topology/src/main/java/org/openkilda/wfm/topology/flow/bolts/FlowOperationsBolt.java
  src-java/flow-topology/flow-storm-topology/src/main/java/org/openkilda/wfm/topology/flow/service/BaseFlowService.java
  src-java/flow-topology/flow-storm-topology/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  src-java/flow-topology/flow-storm-topology/src/test/java/org/openkilda/wfm/topology/flow/service/BaseFlowServiceTest.java
  src-java/flow-topology/flow-storm-topology/src/test/java/org/openkilda/wfm/topology/flow/service/FlowServiceTest.java
  src-java/kilda-model/src/main/java/org/openkilda/model/FlowPair.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/FlowPairRepository.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/RepositoryFactory.java
  src-java/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jFlowPairRepository.java
  src-java/kilda-persistence-neo4j/src/main/java/org/openkilda/persistence/repositories/impl/Neo4jRepositoryFactory.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/FlowOperationsBolt.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsService.java
  src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/FlowOperationsServiceTest.java
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: C/FLOW, C/NBWORKER, Ready to Merge, improvement

#3163 Get rid of UnidirectionalFlow wrapper.
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/mappers/FlowMapper.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/flow/TestFlowBuilder.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/flow/resources/FlowResourcesManagerTest.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/mappers/FlowMapperTest.java
  src-java/flow-topology/flow-storm-topology/src/main/java/org/openkilda/wfm/topology/flow/service/FlowService.java
  src-java/flow-topology/flow-storm-topology/src/test/java/org/openkilda/wfm/topology/flow/service/FlowCommandFactoryTest.java
  src-java/flow-topology/flow-storm-topology/src/test/java/org/openkilda/wfm/topology/flow/validation/FlowValidatorTest.java
  src-java/kilda-model/src/main/java/org/openkilda/model/UnidirectionalFlow.java
  src-java/stats-topology/stats-storm-topology/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyTest.java
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: C/FLOW, Ready to Merge, improvement

#3169 Move transit table_id to 5
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/egress/EgressFlowSegmentCommand.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/egress/EgressFlowSegmentInstallCommandTest.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/test/standard/OutputCommands.java
Labels: C/FL, Ready to Merge, area/multi_table_pipeline, improvement

#3155 Added a status tag to the flow.latency metric in the Ping topology.
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/OnDemandResultManager.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/PeriodicResultManager.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/ResultManager.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/StatsProducer.java
Labels: C/PING, Ready to Merge, improvement

#3160 Return empty list instead of null on dumpMeters request
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/switchmanager/SwitchManagerTest.java
Labels: C/FL, Ready to Merge, improvement

#3222 Docker base image for Lab-Api bumped to Ubuntu Eoan
  docker/base/kilda-base-lab-service/Dockerfile
Labels: On Review, area/cicd, refactor

#3091 Now verify cleanup per feature rather than per spec
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/fixture/CleanupVerifierExtension.groovy
Labels: Ready to Merge, area/testing

#3219 Expose processed kafka record reference
  src-java/base-topology/base-storm-topology/src/checkstyle/checkstyle-suppressions.xml
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/CommandContext.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/AbstractMessageTranslator.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/CorrelationContext.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/GenericKafkaRecordTranslator.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/InfoDataTranslator.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/JsonKafkaTranslator.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/KafkaRecordTranslator.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/LoggerContextInitializer.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/MessageKafkaTranslator.java
  src-java/flow-topology/flow-storm-topology/src/test/java/org/openkilda/wfm/topology/utils/LoggerContextInitializerTest.java
Labels: Ready to Merge, improvement

#3213 Extend detaild of swmanager log messages
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/AbstractBolt.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/hubandspoke/WorkerBolt.java
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
Labels: C/SWMANAGER, Ready to Merge, improvement

#3225 Accept custom Floodlight and Loxigen Git repositoies.
  src-java/projectfloodlight/floodlight/build.gradle
  src-java/projectfloodlight/openflowj/build.gradle
Labels: On Review, area/cicd

#3229 Lower the log level for unhandled tuples in H&S Flow topology
  CHANGELOG.md
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/AbstractBolt.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/hubandspoke/WorkerBolt.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/share/hubandspoke/WorkerBoltTest.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/SpeakerWorkerBolt.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SpeakerWorkerBolt.java
  src-java/network-topology/network-storm-topology/src/main/java/org/openkilda/wfm/topology/network/storm/bolt/swmanager/SwitchManagerWorker.java
Labels: On Review, bugfix

#3242 Downgrade Neo4j and Neo4j-OGM dependencies to pre-restructuring versions
  src-java/build.gradle
  src-java/grpc-speaker/grpc-service/build.gradle
  src-java/northbound-service/northbound/build.gradle
  src-java/testing/performance-tests/build.gradle
Labels: C/FLOW, C/FLOW-HS, C/NBWORKER, C/NETWORK, C/PING, C/REROUTE, C/SWMANAGER, Ready to Merge, area/cicd, bugfix

#3236 Revert "Tempopary disable changing of `enable_bfd` flag"
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/BfdSpec.groovy
Labels: C/NB, Ready to Merge, improvement
