Repository telstra/open-kilda, pull requests merged in 2021-01, with the labels that each got.

#3976 Add GitHub actions for Unittests
  .github/workflows/unittest.yml
  .travis.yml
Labels: Ready to Merge, area/testing, feature

#3978 Fixed Otsdb shouldSendDatapointRequestsTwice test.
  src-java/opentsdb-topology/opentsdb-storm-topology/src/test/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopologyTest.java
Labels: Next Release, Ready to Merge, area/testing, bugfix

#3984 HotFix: Change default parallelism for otsdb and flow hs topologies
  confd/vars/main.yaml
Labels: C/FLOW-HS, C/OTSDB, Next Release, area/storm, improvement

#3995 Increased port count in metadata from 128 to 4096
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/utils/metadata/RoutingMetadata.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/utils/metadata/RoutingMetadataTest.java
Labels: Ready to Merge, area/floodlight, bugfix

#4000 Fix one switch flow update
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/service/SpeakerFlowSegmentRequestBuilder.java
Labels: C/FLOW-HS, Ready to Merge, bugfix

#4007 Update base image to 20.04
  .github/workflows/unittest.yml
  docker/base/kilda-base-ubuntu/Dockerfile
  docker/opentsdb/Dockerfile
  docker/opentsdb/app/create_tables.py
  docker/opentsdb/app/start-opentsdb
  docker/storm/Dockerfile
  src-java/projectfloodlight/floodlight/build.gradle
  src-java/projectfloodlight/openflowj/build.gradle
Labels: Next Release, improvement

#3991 Make sw validation stop ignoring default rules in other than 'proper' sections
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowLoopSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/IntentionalRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MultiRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathV2Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/resilience/RetriesSpec.groovy
Labels: Next Release, improvement

#4012 Added waiting for messaging version from ZooKeeper
  src-java/blue-green/src/main/java/org/openkilda/bluegreen/ZkWatchDog.java
  src-java/blue-green/src/main/java/org/openkilda/bluegreen/kafka/interceptors/VersioningConsumerInterceptor.java
  src-java/blue-green/src/main/java/org/openkilda/bluegreen/kafka/interceptors/VersioningInterceptorBase.java
  src-java/blue-green/src/main/java/org/openkilda/bluegreen/kafka/interceptors/VersioningProducerInterceptor.java
  src-java/blue-green/src/test/java/org/openkilda/bluegreen/kafka/interceptors/VersioningConsumerInterceptorTest.java
  src-java/blue-green/src/test/java/org/openkilda/bluegreen/kafka/interceptors/VersioningProducerInterceptorTest.java
Labels: Ready to Merge, area/zero_downtime, bugfix
