Repository telstra/open-kilda, pull requests merged in 2023-04, with the labels that each got.

#4833 Do not expose storm ports
  confd/templates/docker-compose/docker-compose.tmpl
Labels: Ready to Merge, On Review, improvement, tested

#5158 Add db migration instructions into changelog generator Based on Labels
  tools/changelog-generator/changelog-generator.py
  tools/changelog-generator/requirements.txt
  tools/changelog-generator/template.jinja2
Labels: Next Release, improvement

#4596 rsync requirement during build added to README
  README.md
Labels: area/docs, Next Release, improvement

#5149 HA flows Part 6: Modify the way of storing HA-flow data in DB
  docker/db-migration/migrations/027-add-ha-flow-feature-toggle-and-groups.yaml
  docker/db-migration/migrations/root.yaml
  docs/design/ha-flow/ha-flow-nb-api.md
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/model/system/FeatureTogglesDto.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/HaFlowCreateHubBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/HaFlowUpdateHubBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/mapper/HaFlowMapper.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/mapper/RequestedFlowMapper.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/model/RequestedFlow.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/mapper/HaFlowMapperTest.java
  src-java/kilda-model/build.gradle
  src-java/kilda-model/src/main/java/org/openkilda/model/Flow.java
  src-java/kilda-model/src/main/java/org/openkilda/model/FlowPath.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaFlow.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaFlowPath.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaSubFlow.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaSubFlowEdge.java
  src-java/kilda-model/src/main/java/org/openkilda/model/KildaFeatureToggles.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/HaFlowRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/FlowPathFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/HaFlowFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/HaFlowPathFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/HaSubFlowEdgeFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/HaSubFlowFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/KildaFeatureTogglesFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowPathRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowRepository.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepositoryTest.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaFlowRepositoryTest.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowPathRepositoryTest.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowRepositoryTest.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaHaSubFlowRepositoryTest.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/ferma/repositories/FermaModelUtils.java
  src-java/kilda-persistence-tinkerpop/src/test/java/org/openkilda/persistence/inmemory/InMemoryGraphBasedTest.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/HaFlowMapper.java
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
Labels: feature, Next Release, On Review, DB Migration, C/FLOW-HS

#5156 HA flows Part 9: Add H&S delete operation
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/model/system/FeatureTogglesDto.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/logger/FlowOperationsDashboardLogger.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/HaFlowDeleteHubBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/HaFlowProcessingFsm.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/common/actions/FlowProcessingWithHistorySupportAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/ResourcesAllocationAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/ResourcesDeallocationAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/HaFlowDeleteContext.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/HaFlowDeleteFsm.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/CompleteHaFlowPathRemovalAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/DeallocateResourcesAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/HandleNotCompletedCommandsAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/HandleNotDeallocatedResourcesAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/HandleNotRemovedPathsAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/NotifyHaFlowStatsAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/OnFinishedAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/OnFinishedWithErrorAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/OnReceivedResponseAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/RemoveHaFlowAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/RemoveRulesAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/RevertHaFlowStatusAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/ValidateHaFlowAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/model/Segment.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/service/haflow/HaFlowDeleteService.java
  src-java/kilda-model/src/main/java/org/openkilda/model/KildaFeatureToggles.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/HaFlowRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/frames/KildaFeatureTogglesFrame.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowRepository.java
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowDiversitySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowUpdateSpec.groovy
Labels: feature, Next Release, On Review, C/FLOW-HS

#5161 HA flows Part 10: Add OF rules
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/service/IntersectionComputer.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/service/SpeakerFlowSegmentRequestBuilder.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/EmitInstallRulesRequestsAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/delete/actions/RemoveRulesAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/validation/HaFlowValidator.java
  src-java/kilda-model/src/main/java/org/openkilda/adapter/FlowDestAdapter.java
  src-java/kilda-model/src/main/java/org/openkilda/adapter/FlowSideAdapter.java
  src-java/kilda-model/src/main/java/org/openkilda/adapter/FlowSourceAdapter.java
  src-java/kilda-model/src/main/java/org/openkilda/adapter/HaFlowSharedAdapter.java
  src-java/kilda-model/src/main/java/org/openkilda/adapter/HaFlowSubFlowAdapter.java
  src-java/kilda-model/src/main/java/org/openkilda/model/FlowPath.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaFlow.java
  src-java/kilda-pce/src/main/java/org/openkilda/pce/impl/AvailableNetwork.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/repositories/HaFlowPathRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaHaFlowPathRepository.java
  src-java/rule-manager/rule-manager-implementation/build.gradle
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/DataAdapter.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/adapter/InMemoryDataAdapter.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/adapter/PersistenceDataAdapter.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/FlowRulesGeneratorFactory.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/MeteredRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/EgressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/EgressYRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/IngressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/MultiTableIngressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/MultiTableIngressYRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/MultiTableServer42IngressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/SingleTableIngressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/SingleTableIngressYRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/SingleTableServer42IngressRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/TransitRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/TransitYRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/EgressHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/IngressHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/TransitHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardEgressHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardIngressHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardTransitHaRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/loop/FlowLoopTransitRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/mirror/EgressMirrorRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/flow/mirror/IngressMirrorRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/service/UnicastVerificationVxlanRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/service/arp/ArpPostIngressVxlanRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/service/lldp/LldpPostIngressVxlanRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/factory/generator/service/server42/Server42FlowRttOutputVxlanRuleGenerator.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/utils/Utils.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/RuleManagerHaFlowRulesTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/EgressHaRuleGeneratorTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/HaRuleGeneratorBaseTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/IngressHaRuleGeneratorTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/TransitHaRuleGeneratorTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardEgressHaRuleGeneratorTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardIngressHaRuleGeneratorTest.java
  src-java/rule-manager/rule-manager-implementation/src/test/java/org/openkilda/rulemanager/factory/generator/flow/haflow/YPointForwardTransitHaRuleGeneratorTest.java
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/HaFlowHelper.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowDiversitySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowUpdateSpec.groovy
Labels: feature, Next Release

#5166 Fix incorrect HA-flow protected path allocation
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowPathBuilder.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowPathBuilderTest.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/create/actions/ResourcesAllocationAction.java
  src-java/kilda-persistence-orientdb/src/main/java/org/openkilda/persistence/orientdb/repositories/OrientDbFlowPathRepository.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaFlowPathRepository.java
Labels: feature, Next Release, tested, C/FLOW-HS

#5168 [TEST] Improve post-test cleanups
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowLoopSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/YFlowStatSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesFlowsV2Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/ChaosSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/ContentionSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/FloodlightKafkaConnectionSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/RetriesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/StormHeavyLoadSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/StormLcmSpec.groovy
Labels: area/testing, Next Release, improvement

#5171 Add HA-flow feature toggle for Update operation
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/HaFlowUpdateHubBolt.java
Labels: Next Release, bugfix

#5167 Add GET HA-Flow Paths API endpoint
  src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/command/haflow/HaFlowPathsReadRequest.java
  src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/command/haflow/HaFlowPathsResponse.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopologyConfig.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/HaFlowReadBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/RouterBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/service/haflow/HaFlowReadService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/service/haflow/HaFlowReadServiceTest.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/HaFlowMapper.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/HaFlowServiceImpl.java
  src-java/northbound-service/northbound/src/test/java/org/openkilda/northbound/converter/HaFlowMapperTest.java
Labels: feature, Next Release, tested

#5144 add flow monitoring cache activation and deactivation
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/main/java/org/openkilda/wfm/topology/flowmonitoring/bolt/FlowCacheBolt.java
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/main/java/org/openkilda/wfm/topology/flowmonitoring/bolt/IslCacheBolt.java
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/main/java/org/openkilda/wfm/topology/flowmonitoring/service/FlowCacheService.java
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/main/java/org/openkilda/wfm/topology/flowmonitoring/service/IslCacheService.java
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/test/java/org/openkilda/wfm/topology/flowmonitoring/service/FlowCacheServiceTest.java
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/src/test/java/org/openkilda/wfm/topology/flowmonitoring/service/IslCacheServiceTest.java
Labels: Ready to Merge, improvement, tested, C/FLOW-MONITOR

#5139 Add HA-flow related parallelism options into FlowHs topology
  confd/templates/flowhs-topology/flowhs-topology.tmpl
  confd/vars/main.yaml
Labels: area/config, feature, Ready to Merge, tested

#5129 #2072: Add single-switch flow into diversity group tests
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/PathHelper.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowDiversitySpec.groovy
Labels: area/testing, Ready to Merge

#4886 Handling RequestRejectedException and proper logging of correlation_id
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestRejectedExceptionFilter.java
Labels: Ready to Merge, C/NB, tested, bugfix

#5178 fix logstash container build
  docker/logstash/Dockerfile
Labels: Ready to Merge, Next Release, tested, bugfix

#5119 Feature/5025use rule manager for flow validation
  src-java/floodlight-service/floodlight-api/src/main/java/org/openkilda/messaging/info/flow/FlowDumpResponse.java
  src-java/floodlight-service/floodlight-api/src/main/java/org/openkilda/messaging/info/group/GroupDumpResponse.java
  src-java/floodlight-service/floodlight-api/src/main/java/org/openkilda/messaging/info/meter/MeterDumpResponse.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/rulemanager/SwitchDataProvider.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/converter/rulemanager/OfMeterConverter.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/RecordHandler.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/switchmanager/SwitchManager.java
  src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/info/flow/FlowValidationResponse.java
  src-java/flowhs-topology/flowhs-messaging/src/main/java/org/openkilda/messaging/model/FlowDirectionType.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/FlowHsTopology.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/FlowValidationHubBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/bolts/YFlowValidationHubBolt.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/validation/FlowValidationFsm.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/validation/FlowValidationService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/validation/SimpleSwitchRuleComparator.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/validation/SimpleSwitchRuleConverter.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/validation/YFlowValidationFsm.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/validation/YFlowValidationService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/validation/actions/OnReceivedYFlowResourcesAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/service/FlowValidationHubService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/fsm/validation/FlowValidationServiceTest.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/fsm/validation/FlowValidationTestBase.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/fsm/validation/SimpleSwitchRuleConverterTest.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/fsm/validation/SwitchFlowEntriesBuilder.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/fsm/yflow/validation/YFlowSwitchFlowEntriesBuilder.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/service/FlowValidationHubServiceTest.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/flowhs/service/yflow/YFlowValidationHubServiceTest.java
  src-java/kilda-persistence-api/src/test/java/org/openkilda/persistence/dummy/IdProvider.java
  src-java/northbound-service/northbound-api/src/main/java/org/openkilda/northbound/dto/v1/flows/FlowValidationDto.java
  src-java/northbound-service/northbound-api/src/test/java/org/openkilda/northbound/dto/JsonSerializationTest.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowDirectionMapper.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/converter/FlowMapper.java
  src-java/rule-manager/rule-manager-implementation/src/main/java/org/openkilda/rulemanager/RuleManagerImpl.java
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/mappers/FlowEntryConverter.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/SwitchValidateServiceTest.java
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/FlowHelperV2.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpecV2.groovy
Labels: Ready to Merge, improvement, tested
