Repository telstra/open-kilda, pull requests merged in 2023-08, with the labels that each got.

#5325 fix: modify topology.tmpl to not include the VictoriaMetrics when no victoriametrics exists
  confd/templates/base-storm-topology/topology.properties.tmpl
  src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
Labels: Next Release, improvement

#5287 [PART 5] open-kilda-5242 Migrate all unit tests from JUnit4 to JUnit5 v5
  src-java/server42/server42-control-storm-topology/build.gradle
  src-java/server42/server42-control/src/checkstyle/checkstyle-suppressions.xml
  src-java/server42/server42-control/src/test/java/org/openkilda/server42/control/kafka/GateTest.java
  src-java/server42/server42-stats/build.gradle
  src-java/server42/server42-stats/src/checkstyle/checkstyle-suppressions.xml
  src-java/server42/server42-stats/src/test/java/org/openkilda/server42/stats/zeromq/StatsCollectorTest.java
  src-java/swmanager-topology/swmanager-messaging/build.gradle
  src-java/swmanager-topology/swmanager-messaging/src/checkstyle/checkstyle-suppressions.xml
  src-java/swmanager-topology/swmanager-messaging/src/test/java/org/openkilda/messaging/swmanager/request/CreateLagPortRequestTest.java
  src-java/swmanager-topology/swmanager-messaging/src/test/java/org/openkilda/messaging/swmanager/response/LagPortResponseTest.java
  src-java/swmanager-topology/swmanager-storm-topology/build.gradle
  src-java/swmanager-topology/swmanager-storm-topology/src/checkstyle/checkstyle-suppressions.xml
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsmTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsmTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/FlowEntryConverterTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/GroupEntryConverterTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/LogicalPortMapperTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/MeterEntryConverterTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/RuleEntryConverterTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/mappers/ValidationMapperTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/SwitchRuleServiceTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/SwitchSyncServiceTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/SwitchValidateServiceTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/UpdateLagPortServiceTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/handler/LagPortUpdateHandlerTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/test/java/org/openkilda/wfm/topology/switchmanager/service/impl/ValidationServiceImplTest.java
Labels: Next Release, improvement

#5326 Split connected devices messages
  confd/templates/base-storm-topology/topology.properties.tmpl
  confd/vars/main.yaml
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/Utils.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/GroupsValidationEntryV2.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/LogicalPortsValidationEntryV2.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/MetersValidationEntryV2.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/RulesValidationEntryV2.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/SwitchValidationResponseV2.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/info/switches/v2/ValidationEntry.java
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/split/SplitIterator.java
  src-java/nbworker-topology/nbworker-messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchConnectedDeviceDto.java
  src-java/nbworker-topology/nbworker-messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchConnectedDevicesResponse.java
  src-java/nbworker-topology/nbworker-messaging/src/main/java/org/openkilda/messaging/nbtopology/response/SwitchPortConnectedDevicesDto.java
  src-java/nbworker-topology/nbworker-messaging/src/test/java/org/openkilda/messaging/nbtopology/response/SwitchConnectedDevicesResponseTest.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/NbWorkerTopology.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/NbWorkerTopologyConfig.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: Next Release, improvement, tested, Env Configuration

#5333 Split GetFlowsPerPortForSwitchResponse because they can be too big for Kafka
  src-java/nbworker-topology/nbworker-messaging/src/main/java/org/openkilda/messaging/nbtopology/response/GetFlowsPerPortForSwitchResponse.java
  src-java/nbworker-topology/nbworker-messaging/src/test/java/org/openkilda/messaging/nbtopology/response/GetFlowsPerPortForSwitchResponseTest.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/bolts/SwitchOperationsBolt.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
Labels: Next Release, On Review, improvement, tested

#5332 5308: [TEST] Don't fail test on traffgen address conflict
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/traffexam/TraffExamServiceImpl.java
Labels: area/testing, Next Release, improvement

#5298 [TEST] Make MFL Stats tests tidy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/stats/MflStatSpec.groovy
Labels: area/testing, Next Release, improvement

#5297 [TEST] Fix failing SwapEndpointSpec tests
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/HaFlowHelper.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
Labels: area/testing, Next Release, improvement

#5220 [TEST] Add simple traffexam for HA-Flows
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/HaFlowHelper.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/TopologyHelper.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/SwitchTriplet.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/traffic/ha/HaFlowBidirectionalExam.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/traffic/ha/HaFlowExamReport.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowDiversitySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowPathSwapSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowUpdateSpec.groovy
  src-java/testing/test-library/src/main/java/org/openkilda/testing/model/topology/TopologyDefinition.java
  src-java/testing/test-library/src/main/java/org/openkilda/testing/tools/FlowTrafficExamBuilder.java
Labels: area/testing, Next Release, improvement

#5312 update spring gui repository
  src-gui/build.gradle
Labels: area/cicd, area/ops, area/gui, Next Release, improvement

#5290 Correct the message in the ValidateFlowAction
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/ValidateFlowAction.java
Labels: bug, Next Release, tested, bugfix, C/HISTORY

#5262 Fix issue with HA-Flow update
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/update/actions/OnFinishedAction.java
  src-java/kilda-model/src/main/java/org/openkilda/model/HaSubFlow.java
Labels: Next Release, tested, bugfix

#5243 fix: add ping haflow compatibility in FailReporter
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FailReporter.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/bolt/FlowFetcher.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/model/CacheExpirationRequest.java
  src-java/ping-topology/ping-storm-topology/src/main/java/org/openkilda/wfm/topology/ping/model/FlowWithTransitEncapsulation.java
Labels: Next Release, C/PING, tested, bugfix

#5316 Run unit tests on pushes in develop, master and release-* branches
  .github/workflows/unittest.yml
Labels: Next Release, improvement

#5309 Add an error reason when setting a degraded status on paths
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/CompleteFlowPathInstallationAction.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/reroute/actions/OnFinishedAction.java
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MaxLatencySpec.groovy
Labels: bug, Next Release, tested, bugfix, C/HISTORY

#5344 Add rejected command description in FL logs
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/Command.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/CommandWrapper.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/PendingCommandSubmitter.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/pathverification/PathVerificationService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/CommandProcessorService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/connected/ConnectedDevicesService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/lacp/LacpService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/service/session/SessionService.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/utils/Utils.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/PendingCommandSubmitterTest.java
Labels: area/floodlight, Ready to Merge, improvement, tested

#5314 Disable single table mode in API
  src-java/kilda-model/src/main/java/org/openkilda/model/KildaConfiguration.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/KildaConfigurationService.java
  src-java/nbworker-topology/nbworker-storm-topology/src/main/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsService.java
  src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/KildaConfigurationServiceTest.java
  src-java/nbworker-topology/nbworker-storm-topology/src/test/java/org/openkilda/wfm/topology/nbworker/services/SwitchOperationsServiceTest.java
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/configuration/ConfigurationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/QinQFlowSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableFlowsSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/multitable/MultitableSwitchRulesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchPropertiesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/RetriesSpec.groovy
Labels: area/config, Ready to Merge, improvement, tested

#4882 Remove excessive logging in unit tests
  src-java/connecteddevices-topology/connecteddevices-storm-topology/build.gradle
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/build.gradle
  src-java/flowhs-topology/flowhs-storm-topology/build.gradle
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/build.gradle
  src-java/history-topology/history-storm-topology/build.gradle
  src-java/isllatency-topology/isllatency-storm-topology/build.gradle
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/tx/Transaction.java
  src-java/kilda-persistence-api/src/main/java/org/openkilda/persistence/tx/TransactionManager.java
  src-java/kilda-persistence-hibernate/src/main/java/org/openkilda/persistence/hibernate/HibernateTransactionAdapter.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/FermaTransactionAdapter.java
  src-java/nbworker-topology/nbworker-storm-topology/build.gradle
  src-java/network-topology/network-storm-topology/build.gradle
  src-java/northbound-service/northbound/src/test/resources/log4j2.xml
  src-java/opentsdb-topology/opentsdb-storm-topology/build.gradle
  src-java/ping-topology/ping-storm-topology/build.gradle
  src-java/portstate-topology/portstate-storm-topology/build.gradle
  src-java/reroute-topology/reroute-storm-topology/build.gradle
  src-java/server42/server42-control-storm-topology/build.gradle
  src-java/stats-topology/stats-storm-topology/build.gradle
  src-java/swmanager-topology/swmanager-storm-topology/build.gradle
Labels: area/testing, Ready to Merge, improvement, tested
