Repository telstra/open-kilda, pull requests merged in 2024-02, with the labels that each got.

#5552 3566 Add validation for remotelog server ip
  src-java/grpc-speaker/grpc-service/src/main/java/org/openkilda/grpc/speaker/client/GrpcSession.java
  src-java/grpc-speaker/grpc-service/src/test/java/org/openkilda/grpc/speaker/client/GrpcSessionTest.java
Labels: Ready to Merge, tested, bugfix

#5564 disable PingTopologyTests and StatsTopologyTests
  src-java/ping-topology/ping-storm-topology/src/test/java/org/openkilda/wfm/topology/ping/PingTopologyTest.java
  src-java/stats-topology/stats-storm-topology/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyBaseTest.java
  src-java/stats-topology/stats-storm-topology/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyFlowTest.java
  src-java/stats-topology/stats-storm-topology/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologyHaFlowTest.java
  src-java/stats-topology/stats-storm-topology/src/test/java/org/openkilda/wfm/topology/stats/StatsTopologySwitchTest.java
Labels: area/testing, Next Release, bugfix

#5529 Allow BAD_OUT_PORT from OF errors
  src-java/floodlight-service/floodlight-api/src/main/java/org/openkilda/floodlight/flow/response/FlowErrorResponse.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowSegmentReport.java
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/command/flow/FlowSegmentReportErrorDecoder.java
  src-java/floodlight-service/floodlight-modules/src/test/java/org/openkilda/floodlight/command/flow/FlowErrorResponseTest.java
Labels: Ready to Merge, tested, bugfix

#5565 5551 Add code check style guide
  src-java/checkstyle/README.md
Labels: Ready to Merge, improvement

#5548 5390: [TEST]: Replace switch validation with switch synchronization where possible
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/extension/env/EnvExtension.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/SwitchHelper.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/SwitchPair.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/BaseSpecification.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/listeners/DoCleanupListener.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ConnectedDevicesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV1Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowDiversitySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowLoopSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowValidationNegativeSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MirrorEndpointsSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/PartialUpdateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ProtectedPathV1Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/QinQFlowSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/SwapEndpointSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/ThrottlingRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowIntentionalRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowPathSwapSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowProtectedSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowSyncSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowUpdateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/SubFlowSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowCreateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowPathSwapSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowProtectedSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowRerouteSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowUpdateSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/yflows/YFlowValidationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/IslReplugSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/LinkSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/links/RoundTripIslSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42FlowRttSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42IslRttSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/DefaultRulesValidationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/LagPortSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/MetersSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchActivationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchFailuresSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchSyncSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSingleSwFlowSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchValidationV2Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/SwitchesSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/ContentionSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/xresilience/RetriesSpec.groovy
Labels: area/testing, Ready to Merge, improvement

#5576 [Java 8-17] Zookeeper startup script fix create-zknode-and-start.sh
  docker/zookeeper/bin/create-zknode-and-start.sh
Labels: On Review, bugfix

#5572 5530 Fix css style warning
  src-gui/ui/src/styles.css
Labels: Next Release, improvement

#5114 Added OpenKilda contribution workflow description
  README.md
  docs/README.md
  docs/contrib/memo_for_contributors.rst
  docs/contrib/workflow.md
Labels: area/docs, Next Release, On Review, improvement

#5000 Added design for long mirror with join traffic
  docs/design/flow-traffic-mirroring/flow-traffic-mirroring.md
  docs/design/flow-traffic-mirroring/forward_egress_mirror.png
  docs/design/flow-traffic-mirroring/forward_ingress_mirror.png
  docs/design/flow-traffic-mirroring/reverse_egress_mirror.png
  docs/design/flow-traffic-mirroring/reverse_ingress_mirror.png
Labels: area/docs, feature, Next Release

#4919 Design of traffic mix in feature
  docs/design/flow-traffic-mix-in/README.md
  docs/design/flow-traffic-mix-in/flow_mix_in_example.png
  docs/design/flow-traffic-mix-in/mix_in_ingress_table.png
  docs/design/flow-traffic-mix-in/mix_in_input_table.png
  docs/design/flow-traffic-mix-in/mix_in_pre_ingress_table.png
Labels: area/docs, feature, Next Release

#5578 5575: [TEST]: Fix retry mechanism in tests
  src-java/testing/functional-tests/build.gradle
Labels: area/testing, Next Release

#5568 [Java 8-17] Migrate from docker-compose to docker compose v2.
  README.md
  confd/templates/makefile/makefile.tmpl
  docker/base/hacks/load_kilda_dev_ubuntu.sh
  docker/base/hacks/usecase/flow.crud.make
  docker/base/hacks/usecase/network.disco.make
  docker/db-migration/migrations/README.md
  docker/db-mysql-migration/migrations/README.md
Labels: On Review

#5577 [Java 8-17] Improvement/migration java 8 17 gradle
  src-gui/src/main/java/org/openkilda/integration/model/response/SwitchFlowsPerPort.java
  src-gui/src/main/java/org/openkilda/model/SwitchFlowsInfoPerPort.java
  src-java/base-topology/base-messaging/build.gradle
  src-java/base-topology/base-messaging/src/main/java/org/openkilda/messaging/payload/network/PathValidationPayload.java
  src-java/base-topology/base-storm-topology/build.gradle
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/share/metrics/PushToStreamMeterRegistry.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/utils/LoggerContextInitializer.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/TestUtils.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/topology/TestKafkaConsumer.java
  src-java/blue-green/build.gradle
  src-java/build.gradle
  src-java/floodlight-service/floodlight-modules/build.gradle
  src-java/floodlight-service/floodlight-modules/src/main/java/org/openkilda/floodlight/kafka/Consumer.java
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/FloodlightRouterTopology.java
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/src/main/java/org/openkilda/wfm/topology/floodlightrouter/RegionAwareKafkaTopicSelector.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/haflow/validation/HaFlowValidationService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/main/java/org/openkilda/wfm/topology/flowhs/fsm/validation/FlowValidationService.java
  src-java/flowhs-topology/flowhs-storm-topology/src/test/java/org/openkilda/wfm/topology/utils/LoggerContextInitializerTest.java
  src-java/gradle.properties
  src-java/gradle/wrapper/gradle-wrapper.properties
  src-java/grpc-speaker/grpc-service/build.gradle
  src-java/kilda-persistence-hibernate/src/main/java/org/openkilda/persistence/hibernate/entities/history/HibernatePortEvent.java
  src-java/kilda-persistence-tinkerpop/src/main/java/org/openkilda/persistence/ferma/repositories/FermaPortEventRepository.java
  src-java/northbound-service/northbound/build.gradle
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/WebConfig.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/LinkController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v1/SwitchController.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/link/BfdPropertiesMonitor.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/NorthboundBasicAuthenticationEntryPoint.java
  src-java/northbound-service/northbound/src/test/java/org/openkilda/northbound/controller/v1/FlowControllerTest.java
  src-java/northbound-service/northbound/src/test/java/org/openkilda/northbound/service/LinkServiceTest.java
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/service/LagPortPoolEntityAdapter.java
  src-java/testing/functional-tests/build.gradle
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/SwitchRules.groovy
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/traffexam/model/ExamReport.java
  src-java/testing/test-library/src/main/java/org/openkilda/testing/tools/ExtendedErrorHandler.java
Labels: On Review

#5582 [Java 8-17] Fix the problem with storm introduced accidentally. Replace deprecated code
  src-java/base-topology/base-storm-topology/build.gradle
  src-java/connecteddevices-topology/connecteddevices-storm-topology/build.gradle
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/build.gradle
  src-java/flowhs-topology/flowhs-storm-topology/build.gradle
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/build.gradle
  src-java/history-topology/history-storm-topology/build.gradle
  src-java/isllatency-topology/isllatency-storm-topology/build.gradle
  src-java/nbworker-topology/nbworker-storm-topology/build.gradle
  src-java/network-topology/network-storm-topology/build.gradle
  src-java/opentsdb-topology/opentsdb-storm-topology/build.gradle
  src-java/ping-topology/ping-storm-topology/build.gradle
  src-java/portstate-topology/portstate-storm-topology/build.gradle
  src-java/reroute-topology/reroute-storm-topology/build.gradle
  src-java/server42/server42-control-storm-topology/build.gradle
  src-java/stats-topology/stats-storm-topology/build.gradle
  src-java/swmanager-topology/swmanager-storm-topology/build.gradle
Labels: On Review

#5583 Server42 fixes and more
  src-java/base-topology/base-storm-topology/build.gradle
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/kafka/CustomNamedSubscription.java
  src-java/base-topology/base-storm-topology/src/main/java/org/openkilda/wfm/topology/AbstractTopology.java
  src-java/base-topology/base-storm-topology/src/test/java/org/openkilda/wfm/CommandContextTest.java
  src-java/blue-green/build.gradle
  src-java/blue-green/src/main/java/org/openkilda/bluegreen/UuidKryoSerializer.java
  src-java/build.gradle
  src-java/connecteddevices-topology/connecteddevices-storm-topology/build.gradle
  src-java/floodlight-service/floodlight-modules/build.gradle
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/build.gradle
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/build.gradle
  src-java/grpc-speaker/grpc-service/build.gradle
  src-java/history-topology/history-storm-topology/build.gradle
  src-java/kilda-model/build.gradle
  src-java/network-topology/network-storm-topology/build.gradle
  src-java/northbound-service/northbound/build.gradle
  src-java/opentsdb-topology/opentsdb-storm-topology/build.gradle
  src-java/opentsdb-topology/opentsdb-storm-topology/src/main/java/org/openkilda/wfm/topology/opentsdb/OpenTsdbTopology.java
  src-java/ping-topology/ping-storm-topology/build.gradle
  src-java/portstate-topology/portstate-storm-topology/build.gradle
  src-java/reroute-topology/reroute-storm-topology/build.gradle
  src-java/server42/server42-control-server-stub/build.gradle
  src-java/server42/server42-control-storm-stub/build.gradle
  src-java/server42/server42-control-storm-stub/src/main/java/org/openkilda/server42/control/stormstub/KafkaController.java
  src-java/server42/server42-control-storm-stub/src/main/java/org/openkilda/server42/control/stormstub/swagger/SwaggerApiDocumentationConfig.java
  src-java/server42/server42-control-storm-stub/src/main/java/org/openkilda/server42/control/stormstub/swagger/SwaggerUiController.java
  src-java/server42/server42-control/build.gradle
  src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/Gate.java
  src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/swagger/SwaggerApiDocumentationConfig.java
  src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/swagger/SwaggerUiController.java
  src-java/server42/server42-stats/build.gradle
  src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/swagger/SwaggerApiDocumentationConfig.java
  src-java/server42/server42-stats/src/main/java/org/openkilda/server42/stats/swagger/SwaggerUiController.java
  src-java/stats-topology/stats-storm-topology/src/main/java/org/openkilda/wfm/topology/stats/StatsTopology.java
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchSyncFsm.java
Labels: On Review

#5581 [TEST]: Improvement: Fixing occurred discrepancies after refactoring
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/server42/Server42FlowRttSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/switches/LagPortSpec.groovy
Labels: area/testing, Ready to Merge, improvement

#5585 [Java 8-17] Additional changes to upgrade Storm and performance tweaks.
  confd/templates/storm/storm.yaml.tmpl
  docker/storm/Dockerfile
  docker/storm/simple-storm-supervisor-healthcheck.sh
  docker/storm/simple-storm-ui-healthcheck.sh
  src-java/base-topology/base-storm-topology/build.gradle
  src-java/connecteddevices-topology/connecteddevices-storm-topology/build.gradle
  src-java/floodlightrouter-topology/floodlightrouter-storm-topology/build.gradle
  src-java/flowhs-topology/flowhs-storm-topology/build.gradle
  src-java/flowmonitoring-topology/flowmonitoring-storm-topology/build.gradle
  src-java/history-topology/history-storm-topology/build.gradle
  src-java/isllatency-topology/isllatency-storm-topology/build.gradle
  src-java/nbworker-topology/nbworker-storm-topology/build.gradle
  src-java/network-topology/network-storm-topology/build.gradle
  src-java/opentsdb-topology/opentsdb-storm-topology/build.gradle
  src-java/ping-topology/ping-storm-topology/build.gradle
  src-java/portstate-topology/portstate-storm-topology/build.gradle
  src-java/reroute-topology/reroute-storm-topology/build.gradle
  src-java/server42/server42-control-storm-topology/build.gradle
  src-java/stats-topology/stats-storm-topology/build.gradle
  src-java/swmanager-topology/swmanager-storm-topology/build.gradle
  src-java/testing/test-library/build.gradle
Labels: On Review

#5584 Remove "draft" tag from HA-flow API in swagger.
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/SwaggerConfig.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/HaFlowControllerV2.java
Labels: Ready to Merge, improvement

#5588 [Java 8-17] Add JMX monitoring settings. Adjust Storm settings so that it doesn't consume 100% of all cores.
  confd/templates/docker-compose/docker-compose.tmpl
  confd/templates/storm/storm.yaml.tmpl
  docker/northbound/Dockerfile
  docker/storm/Dockerfile
  docs/design/monitoring/jvm-monitoring.md
Labels: On Review

#5590 Improvement/migration java 8 17 generate topology fix
  src-java/kilda-persistence-hibernate/build.gradle
  src-java/kilda-persistence-hibernate/src/main/java/org/openkilda/persistence/hibernate/entities/EntityBase.java
  src-java/kilda-persistence-hibernate/src/main/java/org/openkilda/persistence/hibernate/entities/history/HibernatePortEvent.java
  src-java/server42/server42-control/build.gradle
  src-java/testing/functional-tests/build.gradle
Labels: On Review

#5594 [Java 8-17] Improvement of northbound modules
  src-java/build.gradle
  src-java/northbound-service/northbound/build.gradle
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/MessageConsumerConfig.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/SecurityConfig.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/config/WebConfig.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/FlowControllerV2.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/YFlowControllerV2.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/BaseFlowEndpointV2Validator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/FlowEndpointV2Validator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/FlowRequestV2Validator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/SubFlowUpdatePayloadValidator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/YFlowCreatePayloadValidator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/YFlowSharedEndpointEncapsulationValidator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/YFlowSharedEndpointValidator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/controller/v2/validator/YFlowUpdatePayloadValidator.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/messaging/kafka/KafkaMessagingChannel.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/LinkServiceImpl.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/service/impl/SwitchServiceImpl.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationFilter.java
  src-java/northbound-service/northbound/src/main/java/org/openkilda/northbound/utils/RequestCorrelationInspectorFilter.java
  src-java/northbound-service/northbound/src/main/resources/application.properties
  src-java/northbound-service/northbound/src/test/java/org/openkilda/northbound/messaging/kafka/KafkaMessagingChannelTest.java
Labels: On Review

#5595 Server 42 Kafka RecordDeserializationException
  confd/templates/server42/server42-control.application.properties.tmpl
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/AddFlow.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/ClearFlows.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/Headers.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/ListFlowsOnSwitch.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/ListFlowsRequest.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/Message.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/PushSettings.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/flowrtt/RemoveFlow.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/islrtt/AddIsl.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/islrtt/ClearIsls.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/islrtt/ListIslPortsOnSwitch.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/islrtt/ListIslsRequest.java
  src-java/server42/server42-control-messaging/src/main/java/org/openkilda/server42/control/messaging/islrtt/RemoveIsl.java
  src-java/server42/server42-control-storm-stub/src/main/java/org/openkilda/server42/control/stormstub/KafkaController.java
  src-java/server42/server42-control/src/main/java/org/openkilda/server42/control/kafka/MessageDeserializer.java
  src-java/server42/server42-control/src/test/java/org/openkilda/server42/control/kafka/GateTest.java
Labels: On Review
