Repository telstra/open-kilda, pull requests merged in 2025-03, with the labels that each got.

#5775 [TEST]: Improvement: DB call optimization
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/builder/HaFlowBuilder.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/factory/HaFlowFactory.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/HaFlowExtended.groovy
  src-java/testing/functional-tests/src/main/groovy/org/openkilda/functionaltests/helpers/model/SwitchRules.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowCrudV1Spec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/FlowMonitoringSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/MaxLatencySpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowSyncSpec.groovy
  src-java/testing/functional-tests/src/test/groovy/org/openkilda/functionaltests/spec/flows/haflows/HaFlowValidationSpec.groovy
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/database/Database.java
  src-java/testing/test-library/src/main/java/org/openkilda/testing/service/database/DatabaseSupportImpl.java
Labels: area/testing, Ready to Merge, improvement

#5771 fix memory leak for swmanager topology.
  src-java/swmanager-topology/swmanager-storm-topology/src/main/java/org/openkilda/wfm/topology/switchmanager/fsm/SwitchValidateFsm.java
Labels: Ready to Merge, improvement, tested

#5778 Issue 2. Xml parser fix
  src-gui/src/main/java/org/openkilda/saml/validator/SamlValidator.java
Labels: Ready to Merge, tested, bugfix
